---
permalink: api-automation/concept_workflow_intro.html 
sidebar: sidebar 
keywords: common, workflows, storage, management 
summary: Os fluxos de trabalho comuns fornecem aos desenvolvedores de aplicativos clientes exemplos de como as APIs do Active IQ Unified Manager podem ser chamadas por um aplicativo cliente para executar funções comuns de gerenciamento de storage. Esta seção contém alguns desses fluxos de trabalho de amostra. 
---
= Workflows de API comuns para gerenciamento de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os fluxos de trabalho comuns fornecem aos desenvolvedores de aplicativos clientes exemplos de como as APIs do Active IQ Unified Manager podem ser chamadas por um aplicativo cliente para executar funções comuns de gerenciamento de storage. Esta seção contém alguns desses fluxos de trabalho de amostra.

Os fluxos de trabalho descrevem alguns dos casos de uso de gerenciamento de armazenamento comumente usados, juntamente com códigos de exemplo para você usar. Cada uma das tarefas é descrita usando um processo de fluxo de trabalho que consiste em uma ou mais chamadas de API.



== Entendendo as chamadas de API usadas nos fluxos de trabalho

Você pode exibir a página de documentação on-line da instância do Unified Manager que inclui os detalhes de cada chamada de API REST. Este documento não repete os detalhes da documentação online. Cada chamada de API usada nos exemplos de fluxo de trabalho neste documento inclui apenas as informações necessárias para localizar a chamada na página de documentação. Depois de localizar uma chamada de API específica, você pode revisar os detalhes completos da chamada, incluindo os parâmetros de entrada, formatos de saída, códigos de status HTTP e tipo de processamento de solicitação.

As seguintes informações são incluídas para cada chamada de API dentro de um fluxo de trabalho para ajudar a localizar a chamada na página de documentação:

* Categoria: As chamadas de API são organizadas na página de documentação em áreas ou categorias funcionalmente relacionadas. Para localizar uma chamada de API específica, role até a parte inferior da página e clique na categoria de API aplicável.
* HTTP verb (chamada): O verbo HTTP identifica a ação executada em um recurso. Cada chamada de API é executada através de um único verbo HTTP.
* Caminho: O caminho determina o recurso específico ao qual a ação se aplica como parte da execução de uma chamada. A cadeia de carateres do caminho é anexada ao URL principal para formar a URL completa que identifica o recurso.

