---
permalink: api-automation/concept_rest_api_access_and_authentication_in_um_apis.html 
sidebar: sidebar 
keywords: rest api, access, authentication, active iq, unified, manager 
summary: A API REST do Active IQ Unified Manager é acessível usando qualquer navegador da Web ou plataforma de programação que possa emitir solicitações HTTP. O Unified Manager oferece suporte ao mecanismo básico de autenticação HTTP. Antes de chamar a API REST do Unified Manager, é necessário autenticar um usuário. 
---
= Acesso à API REST e autenticação no Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A API REST do Active IQ Unified Manager é acessível usando qualquer cliente REST ou plataforma de programação que pode emitir solicitações HTTP com um mecanismo básico de autenticação HTTP.

Uma amostra de solicitação e resposta:

* *Pedido*
+
[listing]
----
GET
https://<IP address/hostname>:<port_number>/api/v2/datacenter/cluster/clusters
----
* *Resposta*
+
[listing]
----
{
  "records": [
    {
      "key": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster,uuid=4c6bf721-2e3f-11e9-a3e2-00a0985badbb",
      "name": "fas8040-206-21",
      "uuid": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb",
      "contact": null,
      "location": null,
      "version": {
        "full": "NetApp Release Dayblazer__9.5.0: Thu Jan 17 10:28:33 UTC 2019",
        "generation": 9,
        "major": 5,
        "minor": 0
      },
      "isSanOptimized": false,
      "management_ip": "10.226.207.25",
      "nodes": [
        {
          "key": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=12cf06cc-2e3a-11e9-b9b4-00a0985badbb",
          "uuid": "12cf06cc-2e3a-11e9-b9b4-00a0985badbb",
          "name": "fas8040-206-21-01",
          "_links": {
            "self": {
              "href": "/api/datacenter/cluster/nodes/4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=12cf06cc-2e3a-11e9-b9b4-00a0985badbb"
            }
          },
          "location": null,
          "version": {
            "full": "NetApp Release Dayblazer__9.5.0: Thu Jan 17 10:28:33 UTC 2019",
            "generation": 9,
            "major": 5,
            "minor": 0
          },
          "model": "FAS8040",
          "uptime": 13924095,
          "serial_number": "701424000157"
        },
        {
          "key": "4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=1ed606ed-2e3a-11e9-a270-00a0985bb9b7",
          "uuid": "1ed606ed-2e3a-11e9-a270-00a0985bb9b7",
          "name": "fas8040-206-21-02",
          "_links": {
            "self": {
              "href": "/api/datacenter/cluster/nodes/4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster_node,uuid=1ed606ed-2e3a-11e9-a270-00a0985bb9b7"
            }
          },
          "location": null,
          "version": {
            "full": "NetApp Release Dayblazer__9.5.0: Thu Jan 17 10:28:33 UTC 2019",
            "generation": 9,
            "major": 5,
            "minor": 0
          },
          "model": "FAS8040",
          "uptime": 14012386,
          "serial_number": "701424000564"
        }
      ],
      "_links": {
        "self": {
          "href": "/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb:type=cluster,uuid=4c6bf721-2e3f-11e9-a3e2-00a0985badbb"
        }
      }
    },
----
+
** `_IP address/hostname_` É o endereço IP ou o nome de domínio totalmente qualificado (FQDN) do servidor API.
** Porta 443
+
443 é a porta HTTPS padrão. Você pode personalizar a porta HTTPS, se necessário.



+
Para emitir solicitações HTTP de um navegador da Web, você precisa usar plugins de navegador REST API. Você também pode acessar a API REST usando plataformas de script como curl e Perl.





== Autenticação

O Unified Manager suporta o esquema básico de autenticação HTTP para APIs. Para um fluxo seguro de informações (solicitação e resposta), as APIS REST são acessíveis somente por HTTPS. O servidor de API fornece um certificado SSL autoassinado a todos os clientes para verificação do servidor. Este certificado pode ser substituído por um certificado personalizado (ou certificado CA).

Você deve configurar o acesso do usuário ao servidor de API para chamar as APIS REST. Os usuários podem ser usuários locais (perfis de usuário armazenados no banco de dados local) ou usuários LDAP (se você tiver configurado o servidor de API para autenticar no LDAP). Você pode gerenciar o acesso do usuário fazendo login na interface de usuário do Unified Manager Administration Console.
