---
permalink: api-automation/concept_get_started_with_um_apis.html 
sidebar: sidebar 
keywords: active iq, unified manager 
summary: O Active IQ Unified Manager fornece um conjunto de APIs para gerenciar seus recursos de storage nos sistemas de storage compatíveis por meio de uma interface de serviço da Web RESTful para qualquer integração de terceiros. 
---
= Primeiros passos com as APIS REST do Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Active IQ Unified Manager fornece um conjunto de APIs para gerenciar seus recursos de storage nos sistemas de storage compatíveis por meio de uma interface de serviço da Web RESTful para qualquer integração de terceiros.

Nesses tópicos, você encontrará informações sobre APIs do Unified Manager, fluxos de trabalho de exemplo para resolver problemas específicos e alguns códigos de exemplo. Usando essas informações, você pode criar clientes RESTful de soluções de software de gerenciamento NetApp para gerenciar sistemas NetApp. As APIs são baseadas no estilo arquitetônico Representational State Transfer (REST). Todas as quatro operações REST Create, Read, Update e Delete (também conhecidas como CRUD) são suportadas.

link:https://docs.netapp.com/us-en/netapp-automation/api/aiqum.html["Active IQ Unified Manager"^]Consulte para obter recursos adicionais e detalhes sobre os benefícios da API REST do Active IQ Unified Manager.
