---
permalink: reporting/concept_unified_manager_databases_accessible_for_reporting.html 
sidebar: sidebar 
keywords: unified manager, databases, access, custom, reporting 
summary: O Unified Manager usa um banco de dados MySQL para armazenar dados dos clusters que ele está monitorando. Os dados são persistidos em vários esquemas no banco de dados MySQL. 
---
= Bancos de dados do Unified Manager acessíveis para relatórios personalizados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Unified Manager usa um banco de dados MySQL para armazenar dados dos clusters que ele está monitorando. Os dados são persistidos em vários esquemas no banco de dados MySQL.

Todos os dados de tabela dos seguintes bancos de dados estão disponíveis:

[cols="2*"]
|===
| Banco de dados | Descrição 


 a| 
NetApp_model
 a| 
Dados sobre os objetos nos controladores ONTAP.



 a| 
NetApp_model_view
 a| 
Dados sobre os objetos em controladores ONTAP, adequados para o consumo de ferramentas de relatório.



 a| 
NetApp_performance
 a| 
Contadores de desempenho específicos de cluster.



 a| 
ocum
 a| 
Dados e informações do aplicativo Unified Manager para oferecer suporte à filtragem, classificação e cálculo de alguns campos derivados da interface do usuário.



 a| 
ocum_report
 a| 
Dados para configuração de inventário e informações relacionadas à capacidade.



 a| 
ocum_report_birt
 a| 
Visualizações para configuração de inventário e dados relacionados à capacidade, adequadas para consumo de ferramentas de relatório.



 a| 
opm
 a| 
Configurações de desempenho e informações de limite.



 a| 
scalemonitor
 a| 
Dados sobre problemas de integridade e performance da aplicação do Unified Manager.



 a| 
vmware_model
 a| 
Dados de objeto VMware para datastores hospedados no storage NetApp.



 a| 
vmware_model_view
 a| 
Visualizações para dados de objetos VMware para datastores hospedados no storage NetApp, adequadas para o consumo de ferramentas de relatório.



 a| 
vmware_performance
 a| 
Dados de contador de desempenho da VMware para datastores hospedados no storage NetApp.

|===
Um usuário de relatório -- um usuário de banco de dados com a função Report Schema -- é capaz de acessar os dados nessas tabelas. Esse usuário tem acesso somente leitura a relatórios e outras visualizações de banco de dados diretamente do banco de dados do Unified Manager. Observe que esse usuário não tem permissão para acessar nenhuma tabela que contenha dados de usuário ou informações de credenciais de cluster.
