---
permalink: performance-checker/concept_how_storage_qos_can_control_workload_throughput.html 
sidebar: sidebar 
keywords: storage, qos, control, workload, throughput 
summary: 'Você pode criar um grupo de políticas de qualidade do serviço (QoS) para controlar o limite de e/S por segundo (IOPS) ou taxa de transferência (MB/s) para os workloads nele contidos. Se as cargas de trabalho estiverem em um grupo de políticas sem limite definido, como o grupo de políticas padrão ou o limite definido não atender às suas necessidades, você poderá aumentar o limite ou mover as cargas de trabalho para um grupo de políticas novo ou existente que tenha o limite desejado.' 
---
= Como a QoS do storage pode controlar a taxa de transferência de workload
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um grupo de políticas de qualidade do serviço (QoS) para controlar o limite de e/S por segundo (IOPS) ou taxa de transferência (MB/s) para os workloads nele contidos. Se as cargas de trabalho estiverem em um grupo de políticas sem limite definido, como o grupo de políticas padrão ou o limite definido não atender às suas necessidades, você poderá aumentar o limite ou mover as cargas de trabalho para um grupo de políticas novo ou existente que tenha o limite desejado.

Os grupos de políticas de QoS ""tradicionais"" podem ser atribuídos a cargas de trabalho individuais, por exemplo, um único volume ou LUN. Nesse caso, a carga de trabalho pode usar o limite de taxa de transferência completa. Grupos de políticas de QoS também podem ser atribuídos a várias cargas de trabalho; nesse caso, o limite de taxa de transferência é "Vermelho" entre as cargas de trabalho. Por exemplo, um limite de QoS de 9.000 IOPS atribuído a três workloads restringiria o IOPS combinado de mais de 9.000 IOPS.

Os grupos de política de QoS "adaptável" também podem ser atribuídos a workloads individuais ou vários workloads. No entanto, mesmo quando atribuído a vários workloads, cada workload recebe o limite de taxa de transferência completa em vez de compartilhar o valor da taxa de transferência com outros workloads. Além disso, as políticas de QoS adaptáveis ajustam automaticamente a configuração de taxa de transferência com base no tamanho do volume, por workload, mantendo a proporção de IOPS para terabytes à medida que o tamanho do volume muda. Por exemplo, se o pico estiver definido para 5.000 IOPS/TB em uma política de QoS adaptável, um volume de 10 TB terá uma taxa de transferência máxima de 50.000 IOPS. Se o volume for redimensionado posteriormente para 20 TB, a QoS adaptável ajusta o máximo para 100.000 IOPS.

A partir do ONTAP 9.5, você pode incluir o tamanho do bloco ao definir uma política de QoS adaptável. Isso converte efetivamente a política de um limite de IOPS/TB para um limite de MB/s para casos em que as cargas de trabalho estão usando tamanhos de bloco muito grandes e, em última análise, usando uma grande porcentagem de taxa de transferência.

Para políticas de QoS de grupo compartilhado, quando o IOPS ou MB/s de todos os workloads em um grupo de políticas excede o limite definido, o grupo de políticas mantém os workloads para restringir a atividade, o que pode diminuir a performance de todos os workloads no grupo de políticas. Se um evento de desempenho dinâmico for gerado pela limitação do grupo de políticas, a descrição do evento exibirá o nome do grupo de políticas envolvido.

Na exibição desempenho: Todos os volumes, você pode classificar os volumes afetados por IOPS e MB/s para ver quais cargas de trabalho têm o maior uso que pode ter contribuído para o evento. Na página Performance/volumes Explorer, é possível selecionar outros volumes ou LUNs no volume para comparar com o uso de IOPS do workload afetado ou taxa de transferência em Mbps.

Ao atribuir as cargas de trabalho que estão sobreusando os recursos do nó a uma configuração de grupo de políticas mais restritiva, o grupo de políticas mantém as cargas de trabalho para restringir sua atividade, o que pode reduzir o uso dos recursos nesse nó. No entanto, se você quiser que a carga de trabalho possa usar mais recursos do nó, você pode aumentar o valor do grupo de políticas.

Você pode usar o Gerenciador de sistema, os comandos do ONTAP ou os níveis de Serviço de Performance do Gerenciador Unificado para gerenciar grupos de políticas, incluindo as seguintes tarefas:

* Criando um grupo de políticas
* Adição ou remoção de cargas de trabalho em um grupo de políticas
* Movimentação de uma carga de trabalho entre grupos de políticas
* Alterar o limite de taxa de transferência de um grupo de políticas
* Mover um workload para um agregado e/ou nó diferente

