---
permalink: performance-checker/concept_understand_performance_events_and_alerts.html 
sidebar: sidebar 
keywords: understand, performance, events, alerts 
summary: Os eventos de desempenho são notificações que o Unified Manager gera automaticamente quando ocorre uma condição predefinida ou quando um valor do contador de desempenho cruza um limite. Os eventos ajudam a identificar problemas de desempenho nos clusters monitorados. 
---
= Compreender eventos e alertas de desempenho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os eventos de desempenho são incidentes relacionados ao desempenho da carga de trabalho em um cluster. Eles ajudam a identificar workloads com tempos de resposta lentos. Juntamente com eventos de saúde que ocorreram ao mesmo tempo, você pode determinar os problemas que podem ter causado ou contribuído para os tempos de resposta lentos.

Quando o Unified Manager deteta várias ocorrências da mesma condição de evento para o mesmo componente de cluster, ele trata todas as ocorrências como um único evento, não como eventos separados.

Você pode configurar alertas para enviar notificações por e-mail automaticamente quando ocorrerem eventos de desempenho de determinados tipos de gravidade.
