---
permalink: performance-checker/concept_remove_inactive_volumes_and_luns.html 
sidebar: sidebar 
keywords: remove, inactive, volumes, luns 
summary: Quando o espaço livre agregado for identificado como um problema, você poderá pesquisar volumes e LUNs não utilizados e excluí-los do agregado. Isso pode ajudar a aliviar o problema de pouco espaço em disco. 
---
= Remover volumes inativos e LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando o espaço livre agregado for identificado como um problema, você poderá pesquisar volumes e LUNs não utilizados e excluí-los do agregado. Isso pode ajudar a aliviar o problema de pouco espaço em disco.

Se um evento de performance em um agregado for causado por pouco espaço em disco, há algumas maneiras de determinar quais volumes e LUNs não estão mais sendo usados.

Para identificar volumes não utilizados:

* Na página Detalhes do evento, o campo *contagem de objetos afetados* fornece um link que exibe a lista de volumes afetados.
+
Clique no link para exibir os volumes na exibição desempenho: Todos os volumes. A partir daí, você pode classificar os volumes afetados por *IOPS* para ver quais volumes não estiveram ativos.



Para identificar LUNs não utilizados:

. Na página de detalhes do evento, anote o nome do agregado no qual o evento ocorreu.
. No painel de navegação esquerdo, clique em *armazenamento* > *LUNs* e selecione *desempenho* > *todos os LUNs* no menu Exibir.
. Clique em *Filtering*, selecione *Aggregate* no menu suspenso à esquerda, digite o nome do agregado no campo de texto e clique em *Apply Filter*.
. Classifique a lista resultante de LUNs afetados por *IOPS* para visualizar os LUNs que não estão ativos.


Depois de identificar os volumes e LUNs não utilizados, você pode usar o Gerenciador de sistema do ONTAP ou os comandos ONTAP para excluir esses objetos.
