---
permalink: performance-checker/concept_what_expected_range_of_performance_is.html 
sidebar: sidebar 
keywords: expected, range, performance, latency, forecast, formed 
summary: A previsão de latência é uma previsão do que os valores de desempenho superior e inferior devem ser em um momento específico. Para a latência do workload, os valores superiores formam o limite de performance. Quando o valor real cruza o limite de performance, o Unified Manager aciona um evento de performance dinâmico. 
---
= Qual é a faixa de desempenho esperada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A previsão de latência é uma previsão do que os valores de desempenho superior e inferior devem ser em um momento específico. Para a latência do workload, os valores superiores formam o limite de performance. Quando o valor real cruza o limite de performance, o Unified Manager aciona um evento de performance dinâmico.

Por exemplo, durante o horário comercial regular entre as 9:00h e as 5:00h, a maioria dos funcionários pode verificar seu e-mail entre as 9:00h e as 10:30H. o aumento da demanda nos servidores de e-mail significa um aumento na atividade de carga de trabalho no armazenamento de back-end durante esse período. Os funcionários podem notar um tempo de resposta lento de seus clientes de e-mail.

Durante a hora de almoço entre as 12:00h e as 1:00h e no final do dia de trabalho após as 5:00h, a maioria dos funcionários provavelmente está longe de seus computadores. A demanda nos servidores de e-mail geralmente diminui, também diminuindo a demanda no armazenamento de back-end. Como alternativa, pode haver operações de carga de trabalho agendadas, como backups de armazenamento ou verificação de vírus, que começam após as 5:00 horas e aumentam a atividade no armazenamento de back-end.

Ao longo de vários dias, o aumento e a diminuição da atividade de workload determinam o intervalo esperado (previsão de latência) da atividade, com limites superior e inferior para uma carga de trabalho. Quando a atividade de carga de trabalho real para um objeto está fora dos limites superior ou inferior e permanece fora dos limites por um período de tempo, isso pode indicar que o objeto está sendo usado em excesso ou subutilizado.



== Como a previsão de latência é formada

O Unified Manager deve coletar no mínimo 3 dias de atividade do workload antes que ele possa iniciar a análise e antes que a previsão de latência do tempo de resposta de e/S possa ser exibida na GUI. A coleta de dados mínima necessária não é responsável por todas as alterações que ocorrem na atividade da carga de trabalho. Após coletar os primeiros 3 dias de atividade, o Unified Manager ajusta a previsão de latência a cada 24 horas às 12:00 da manhã para refletir as alterações na atividade do workload e estabelecer um limite de performance dinâmico mais preciso.

[NOTE]
====
O horário de verão (DST) altera a hora do sistema, o que altera a previsão de latência das estatísticas de desempenho para cargas de trabalho monitoradas. O Unified Manager começa imediatamente a corrigir a previsão de latência, que leva aproximadamente 15 dias para ser concluída. Durante esse período, você pode continuar usando o Unified Manager, mas, como o Unified Manager usa a previsão de latência para detetar eventos dinâmicos, alguns eventos podem não ser precisos. Os eventos detetados antes da alteração de hora não são afetados.

====