---
permalink: performance-checker/reference_what_performance_metrics_can_be_monitored_using_thresholds.html 
sidebar: sidebar 
keywords: performance, counters, tracked, thresholds 
summary: Alguns contadores de desempenho comuns, como IOPS e MB/s, podem ter limites definidos para todos os objetos de armazenamento. Existem outros contadores que podem ter limites definidos apenas para determinados objetos de armazenamento. 
---
= Quais contadores de desempenho podem ser rastreados usando limites
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Alguns contadores de desempenho comuns, como IOPS e MB/s, podem ter limites definidos para todos os objetos de armazenamento. Existem outros contadores que podem ter limites definidos apenas para determinados objetos de armazenamento.



== Contadores de desempenho disponíveis

|===
| Objeto de storage | Contador de desempenho | Descrição 


 a| 
Cluster
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída que o cluster processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este cluster por segundo.



 a| 
Nó
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída que o nó processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este nó por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o nó leva para responder às solicitações de aplicação.



 a| 
Utilização
 a| 
Porcentagem média da CPU e RAM do nó que está sendo usado.



 a| 
Capacidade de performance utilizada
 a| 
Porcentagem média de capacidade de performance consumida pelo nó.



 a| 
Capacidade de desempenho utilizada - takeover
 a| 
Porcentagem média de capacidade de performance consumida pelo nó e a capacidade de performance do nó do parceiro.



 a| 
Agregado
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída os processos agregados por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este agregado por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o agregado leva para responder às solicitações do aplicativo.



 a| 
Utilização
 a| 
Porcentagem média dos discos do agregado que estão sendo usados.



 a| 
Capacidade de performance utilizada
 a| 
Porcentagem média de capacidade de performance consumida pelo agregado.



 a| 
Armazenamento VM
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída processadas pelo SVM por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este SVM por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o SVM leva para responder a solicitações de aplicações.



 a| 
Volume
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída o volume processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este volume por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o volume leva para responder às solicitações do aplicativo.



 a| 
Relação de falta de cache
 a| 
Porcentagem média de solicitações de leitura de aplicativos clientes que são retornadas do volume em vez de serem retornadas do cache.



 a| 
LUN
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída que o LUN processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este LUN por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o LUN leva para responder às solicitações de aplicativos.



 a| 
Namespace
 a| 
IOPS
 a| 
Número médio de operações de entrada/saída que o namespace processa por segundo.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos para e a partir deste namespace por segundo.



 a| 
Latência
 a| 
Número médio de milissegundos que o namespace leva para responder a solicitações de aplicativos.



 a| 
Porta
 a| 
Utilização de largura de banda
 a| 
Porcentagem média da largura de banda disponível da porta que está sendo usada.



 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos para e a partir desta porta por segundo.



 a| 
Interface de rede (LIF)
 a| 
MB/s
 a| 
Número médio de megabytes de dados transferidos de e para este LIF por segundo.

|===