---
permalink: performance-checker/task_view_node_iops_based_on_workloads_on_local_node.html 
sidebar: sidebar 
keywords: view, node, iops, workloads, reside, only, local node 
summary: 'O gráfico de contador de IOPS do nó pode destacar onde as operações estão passando somente pelo nó local usando um LIF de rede para executar operações de leitura/gravação em volumes em um nó remoto. Os gráficos IOPS - "Total (local)" e "Breakdown (local)" exibem o IOPS para dados que residem em volumes locais apenas no nó atual.' 
---
= Visualização de IOPS do nó com base em workloads que residem somente no nó local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O gráfico de contador de IOPS do nó pode destacar onde as operações estão passando somente pelo nó local usando um LIF de rede para executar operações de leitura/gravação em volumes em um nó remoto. Os gráficos de IOPS - total (local)" e "divisão (local)" exibem o IOPS para dados que residem em volumes locais apenas no nó atual.

As versões "locais" desses gráficos de contador são semelhantes aos gráficos de nós para capacidade de desempenho e utilização, pois também mostram apenas as estatísticas de dados que residem em volumes locais.

Ao comparar as versões "locais" desses gráficos de contador com as versões totais regulares desses gráficos de contador, você pode ver se há muito tráfego se movendo através do nó local para acessar volumes no nó remoto. Essa situação pode causar problemas de desempenho, possivelmente indicados pela alta utilização no nó, se houver muitas operações passando pelo nó local para alcançar um volume em um nó remoto. Nesses casos, você pode querer mover um volume para o nó local ou criar um LIF no nó remoto onde o tráfego de hosts que acessam esse volume pode ser conetado.

.Passos
. Na página *Performance/Node Explorer* do nó selecionado, no gráfico IOPS, selecione *Total* no menu suspenso.
+
O gráfico IOPS - Total é exibido.

. Clique em *Zoom View* para exibir uma versão maior do gráfico em uma nova guia do navegador.
. De volta à página *Performance/Node Explorer*, no gráfico IOPS, selecione *Total (local)* no menu suspenso.
+
O gráfico IOPS - Total (local) é exibido.

. Clique em *Zoom View* para exibir uma versão maior do gráfico em uma nova guia do navegador.
. Visualize ambos os gráficos ao lado uns dos outros e identifique áreas onde os valores de IOPS parecem ser bastante diferentes.
. Mova o cursor sobre essas áreas para comparar as IOPS local e total de um ponto específico no tempo.

