---
permalink: storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html 
sidebar: sidebar 
keywords: ontap issues, fix it action, automatic remediation feature, remediation events, fix-it messages, fix-it events 
summary: Esta tabela descreve os problemas do ONTAP que o Unified Manager pode resolver diretamente a partir da interface de usuário do Unified Manager clicando no botão corrigir ou corrigir tudo. 
---
= Quais problemas o Unified Manager pode corrigir
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Usando o recurso de correção automática do Active IQ Unified Manager, você pode optar por resolver certos problemas do ONTAP ou gerenciar certos recursos do ONTAP, como monitoramento anti-ransomware, de forma eficaz por meio do Unified Manager.

Esta tabela descreve esses problemas ou recursos do ONTAP que você pode gerenciar diretamente por meio do botão *Fix it* ou *Fix All* na IU da Web do Unified Manager.

|===
| Nome e Descrição do evento | Ação de Gestão | Operação "corrigir" 


 a| 
Volume espaço cheio

O volume está quase fora do espaço e violou o limite máximo de capacidade. Este limite é definido por padrão para 90% do tamanho do volume.
 a| 
Ativar volume com crescimento automático
 a| 
O Unified Manager determina que o volume com crescimento automático não está configurado para esse volume, portanto, habilita esse recurso para que o volume aumente na capacidade quando necessário.



 a| 
Inodes Full

Este volume ficou sem inodes e não pode aceitar novos arquivos.
 a| 
Aumentar o número de inodes no volume
 a| 
Aumenta o número de inodes no volume em 2%.



 a| 
Detectada não correspondência incorreta da política de nível de armazenamento

O volume tem muitos dados inativos e a política de disposição em camadas atual é definida como "somente snapshot" ou "nenhum".
 a| 
Habilitar a disposição automática de nuvem em categorias
 a| 
Como o volume já reside em um FabricPool, ele muda a política de disposição em categorias para "automático", para que os dados inativos sejam movidos para a camada de nuvem de menor custo.



 a| 
Detectada incompatibilidade de nível de armazenamento

O volume tem muitos dados inativos, mas não reside em uma categoria de storage habilitado para nuvem (FabricPool).
 a| 
Alterar a camada de storage dos volumes
 a| 
Move o volume para a camada de storage habilitada para a nuvem e define a política de disposição em camadas como "automática" para mover dados inativos para a camada de nuvem.



 a| 
Registo de auditoria desativado

O log de auditoria não está habilitado para a VM de armazenamento
 a| 
Ativar o registo de auditoria para a VM de armazenamento
 a| 
Permite o log de auditoria na VM de storage.

Observe que a VM de storage já deve ter um local de log de auditoria local ou remoto configurado.



 a| 
Banner de login desativado

O banner de login do cluster deve estar habilitado para aumentar a segurança, deixando as restrições de acesso claras.
 a| 
Defina o banner de login para o cluster
 a| 
Define o banner de login do cluster como ""Acesso restrito a usuários autorizados"".



 a| 
Banner de login desativado

O banner de login para a VM de armazenamento deve ser habilitado para aumentar a segurança, deixando as restrições de acesso claras.
 a| 
Defina o banner de login para a VM de armazenamento
 a| 
Define o banner de login da VM de armazenamento como "Acesso restrito a usuários autorizados".



 a| 
O SSH está usando Ciphers inseguros

Cifras com o sufixo "-cbc" são consideradas inseguras.
 a| 
Remova cifras inseguras do cluster
 a| 
Remove as cifras inseguras -- como aes192-cbc e AES128-cbc -- do cluster.



 a| 
O SSH está usando Ciphers inseguros

Cifras com o sufixo "-cbc" são consideradas inseguras.
 a| 
Remova cifras inseguras da VM de armazenamento
 a| 
Remove as cifras inseguras - como aes192-cbc e AES128-cbc -- da VM de storage.



 a| 
Transporte HTTPS AutoSupport desativado

O protocolo de transporte utilizado para enviar mensagens AutoSupport para o suporte técnico deve ser encriptado.
 a| 
Defina HTTPS como o protocolo de transporte para mensagens AutoSupport
 a| 
Define HTTPS como o protocolo de transporte de mensagens AutoSupport no cluster.



 a| 
Limite de desequilíbrio de carga do cluster violado

Indica que a carga está desequilibrada entre os nós no cluster. Esse evento é gerado quando a variação da capacidade de performance usada é superior a 30% entre nós.
 a| 
Equilibre workloads de cluster
 a| 
O Unified Manager identifica o melhor volume para mover de um nó para o outro, a fim de reduzir o desequilíbrio e, em seguida, move o volume.



 a| 
Limite de desequilíbrio da capacidade do cluster violado

Indica que a capacidade está desequilibrada entre os agregados no cluster. Este evento é gerado quando a variação da capacidade utilizada é superior a 70% entre agregados.
 a| 
Equilibrar a capacidade do cluster
 a| 
O Unified Manager identifica o melhor volume para mover de um agregado para outro, a fim de reduzir o desequilíbrio e, em seguida, move o volume.



 a| 
Limite de capacidade de performance usado violado

Indica que a carga no nó pode se tornar sobreutilizada se você não reduzir a utilização de uma ou mais cargas de trabalho altamente ativas. Esse evento é gerado quando o valor da capacidade de performance do nó usada for superior a 100% por mais de 12 horas.
 a| 
Limite a carga alta no nó
 a| 
O Unified Manager identifica o volume com o IOPS mais alto e aplica uma política de QoS usando os níveis histórico esperado e máximo de IOPS para reduzir a carga no nó.



 a| 
Limite de aviso de eventos dinâmicos violado

Indica que o nó já está operando em um estado sobrecarregado devido à carga anormalmente alta de algumas das cargas de trabalho.
 a| 
Reduza a sobrecarga no nó
 a| 
O Unified Manager identifica o volume com o IOPS mais alto e aplica uma política de QoS usando os níveis histórico esperado e máximo de IOPS para reduzir a carga no nó.



 a| 
A aquisição não é possível

O failover está atualmente desativado, portanto, o acesso aos recursos do nó durante uma interrupção ou reinicialização seria perdido até que o nó ficasse disponível novamente.
 a| 
Habilite o failover de nó
 a| 
O Unified Manager envia o comando apropriado para habilitar o failover em todos os nós do cluster.



 a| 
A opção Cf.Takeover.ON_PANIC está configurada como DESLIGADA

A opção nodeshell "cf.Takeover.on_panic" está definida como *Off*, o que pode causar um problema em sistemas configurados pelo HA.
 a| 
Ativar a aquisição em pânico
 a| 
O Unified Manager envia o comando apropriado ao cluster para alterar essa configuração para *ON*.



 a| 
Desative a opção nodeshell SnapMirror.enable

A antiga opção nodeshell "SnapMirror.enable" está definida como *ON*, o que pode causar um problema durante a inicialização após a atualização para o ONTAP 9.3 ou superior.
 a| 
Defina a opção SnapMirror.enable (Ativar) como Off (Desligado)
 a| 
O Unified Manager envia o comando apropriado ao cluster para alterar essa configuração para *Off*.



 a| 
Telnet ativado

Indica um potencial problema de segurança porque o Telnet é inseguro e passa dados de maneira não criptografada.
 a| 
Desativar o Telnet
 a| 
O Unified Manager envia o comando apropriado ao cluster para desativar o Telnet.



 a| 
Configurar a aprendizagem anti-ransomware de VM de storage

Verifica periodicamente clusters com licenças para monitoramento anti-ransomware. Valida se uma VM de armazenamento suporta apenas volumes NFS ou SMB em um cluster desse tipo.
 a| 
Colocar as VMs de storage em um `learning` modo de monitoramento anti-ransomware
 a| 
O Unified Manager define o monitoramento anti-ransomware para `learning` indicar as VMs de storage por meio do console de gerenciamento de cluster. O monitoramento contra ransomware em todos os novos volumes criados na VM de storage é automaticamente movido para o modo de aprendizado. Com essa capacitação, o ONTAP pode aprender o padrão de atividade nos volumes e detectar anomalias devido a possíveis ataques mal-intencionados.



 a| 
Configurar o volume de aprendizagem anti-ransomware

Verifica periodicamente clusters com licenças para monitoramento anti-ransomware. Valida se um volume suporta apenas serviços NFS ou SMB em tal cluster.
 a| 
Coloque volumes `learning` no modo de monitoramento anti-ransomware
 a| 
O Unified Manager define o monitoramento anti-ransomware para `learning` indicar os volumes pelo console de gerenciamento de cluster. Com essa capacitação, o ONTAP pode aprender o padrão de atividade nos volumes e detectar anomalias devido a possíveis ataques mal-intencionados.



 a| 
Habilite o volume anti-ransomware

Verifica periodicamente clusters com licenças para monitoramento anti-ransomware. Detecta se os volumes estão `learning` no modo de monitoramento anti-ransomware por mais de 45 dias e determina a perspetiva de colocá-los no modo ativo.
 a| 
Coloque volumes `active` no modo de monitoramento anti-ransomware
 a| 
O Unified Manager define o monitoramento anti-ransomware para `active` os volumes por meio do console de gerenciamento de cluster. Com essa capacitação, o ONTAP pode aprender o padrão de atividade nos volumes, detectar anomalias devido a possíveis ataques maliciosos e criar alertas de ações de proteção de dados.



 a| 
Desativar volume anti-ransomware

Verifica periodicamente clusters com licenças para monitoramento anti-ransomware. Detecta notificações repetitivas durante o monitoramento ativo anti-ransomware nos volumes (por exemplo, vários avisos de possíveis ataques de ransomware são retornados ao longo de 30 dias).
 a| 
Desativar o monitoramento anti-ransomware em volumes
 a| 
O Unified Manager desativa o monitoramento anti-ransomware nos volumes por meio do console de gerenciamento de cluster.

|===