---
permalink: storage-mgmt/task_create_an_email_notification_format.html 
sidebar: sidebar 
keywords: create, email, notification, format, user, group, quotas 
summary: 'Você pode criar um formato de notificação para os e-mails que são enviados para um usuário ou um grupo de usuários quando houver um problema relacionado à cota (limite de software violado ou limite rígido atingido).' 
---
= Criando um formato de notificação por e-mail para cotas de usuários e grupos de usuários
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um formato de notificação para os e-mails que são enviados para um usuário ou um grupo de usuários quando houver um problema relacionado à cota (limite de software violado ou limite rígido atingido).

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

.Passos
. No painel de navegação à esquerda, clique em *Geral* > *formato de e-mail da cota*.
. Insira ou modifique os detalhes nos campos *de*, *Assunto* e *Detalhes do e-mail*.
. Clique em *Preview* para visualizar a notificação por e-mail.
. Clique em *Fechar* para fechar a janela de visualização.
. Modifique o conteúdo da notificação por e-mail, se necessário.
. Clique em *Salvar*.

