---
permalink: storage-mgmt/task_add_space_to_data_disk_of_vmware.html 
sidebar: sidebar 
keywords: add space, data, disk, vmware, virtual, machine 
summary: Se você precisar aumentar a quantidade de espaço no disco de dados para o banco de dados do Unified Manager, poderá adicionar capacidade após a instalação aumentando o espaço em disco usando o console de manutenção do Unified Manager. 
---
= Adicionando espaço ao disco de dados da máquina virtual VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você precisar aumentar a quantidade de espaço no disco de dados para o banco de dados do Unified Manager, poderá adicionar capacidade após a instalação aumentando o espaço em disco usando o console de manutenção do Unified Manager.

*O que você vai precisar*

* Você deve ter acesso ao vSphere Client.
* A máquina virtual não deve ter instantâneos armazenados localmente.
* Tem de ter as credenciais do utilizador de manutenção.


Recomendamos que você faça backup de sua máquina virtual antes de aumentar o tamanho dos discos virtuais.

.Passos
. No cliente vSphere, selecione a máquina virtual do Unified Manager e adicione mais capacidade de disco aos dados `disk 3`. Consulte a documentação da VMware para obter detalhes.
+
Em alguns casos raros, a implantação do Unified Manager usa "disco rígido 2" para o disco de dados em vez de "disco rígido 3". Se isso tiver ocorrido em sua implantação, aumente o espaço de qualquer disco maior. O disco de dados sempre terá mais espaço do que o outro disco.

. No cliente vSphere, selecione a máquina virtual do Unified Manager e, em seguida, selecione a guia *Console*.
. Clique na janela do console e, em seguida, faça login no console de manutenção usando seu nome de usuário e senha.
. No *Menu Principal*, insira o número da opção *Configuração do sistema*.
. No *Menu de Configuração do sistema*, insira o número da opção *aumentar o tamanho do disco de dados*.

