---
permalink: storage-mgmt/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux host 
summary: 'Se você atribuiu espaço em disco insuficiente ao `/opt/netapp/data` diretório para oferecer suporte ao Unified Manager quando configurou originalmente o host Linux e instalou o Unified Manager, você poderá adicionar espaço em disco após a instalação aumentando o espaço em disco `/opt/netapp/data` no diretório.' 
---
= Adicionando espaço ao diretório de dados do host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você atribuiu espaço em disco insuficiente ao `/opt/netapp/data` diretório para oferecer suporte ao Unified Manager quando configurou originalmente o host Linux e instalou o Unified Manager, você poderá adicionar espaço em disco após a instalação aumentando o espaço em disco `/opt/netapp/data` no diretório.

.Antes de começar
Você deve ter acesso de usuário raiz à máquina Red Hat Enterprise Linux na qual o Unified Manager está instalado.

Recomendamos que você faça backup do banco de dados do Unified Manager antes de aumentar o tamanho do diretório de dados.

.Passos
. Faça login como usuário root na máquina Linux na qual você deseja adicionar espaço em disco.
. Pare o serviço Unified Manager e o software MySQL associado na ordem mostrada: `systemctl stop ocieau ocie mysqld`
. Crie uma pasta de backup temporária (por exemplo, `/backup-data`) com espaço em disco suficiente para conter os dados no diretório atual `/opt/netapp/data`.
. Copie o conteúdo e a configuração de privilégios do diretório existente `/opt/netapp/data` para o diretório de dados de backup:
+
`cp -arp /opt/netapp/data/* /backup-data`

. Se o se Linux estiver ativado:
+
.. Obtenha o tipo se Linux para pastas na pasta existente `/opt/netapp/data`:
+
`se_type=`ls -Z /opt/netapp/data| awk '{print $4}'| awk -F: '{print $3}'| head -1`

+
O sistema retorna uma confirmação semelhante à seguinte:

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. Execute o `chcon` comando para definir o tipo se Linux para o diretório de backup:
+
`chcon -R --type=mysqld_db_t /backup-data`



. Remova o conteúdo do `/opt/netapp/data` diretório:
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. Expanda o tamanho `/opt/netapp/data` do diretório para um mínimo de 150 GB por meio de comandos LVM ou adicionando discos extras.
+
[NOTE]
====
Se você criou `/opt/netapp/data` a partir de um disco, então você não deve tentar montar `/opt/netapp/data` como um compartilhamento NFS ou CIFS. Porque, neste caso, se você tentar expandir o espaço em disco, alguns comandos LVM, `resize` como e `extend` podem não funcionar como esperado.

====
. Confirme que o `/opt/netapp/data` proprietário do diretório (mysql) e o grupo (root) estão inalterados:
+
`ls -ltr /opt/netapp/ | grep data`

+
O sistema retorna uma confirmação semelhante à seguinte:

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. Se o se Linux estiver ativado, confirme que o contexto `/opt/netapp/data` do diretório ainda está definido como mysqld_dB_t:
+
.. `touch /opt/netapp/data/abc`
.. `ls -Z /opt/netapp/data/abc`
+
O sistema retorna uma confirmação semelhante à seguinte:

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. Exclua o arquivo `abc` para que esse arquivo estranho não cause um erro de banco de dados no futuro.
. Copie o conteúdo `backup-data` de volta para o diretório expandido `/opt/netapp/data`:
+
`cp -arp /backup-data/* /opt/netapp/data/`

. Se o se Linux estiver ativado, execute o seguinte comando:
+
`chcon -R --type=mysqld_db_t /opt/netapp/data`

. Inicie o serviço MySQL:
+
`systemctl start mysqld`

. Após o início do serviço MySQL, inicie os serviços ocie e ocieau na ordem mostrada:
+
`systemctl start ocie ocieau`

. Depois de todos os serviços serem iniciados, exclua a pasta de `/backup-data` backup :
+
`rm -rf /backup-data`


