---
permalink: storage-mgmt/task_remove_clusters.html 
sidebar: sidebar 
keywords: remove, cluster 
summary: Você pode remover um cluster do Unified Manager usando a página Configuração de cluster. Por exemplo, você pode remover um cluster se a descoberta de cluster falhar ou quando quiser desativar um sistema de storage. 
---
= Remoção de clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover um cluster do Unified Manager usando a página Configuração de cluster. Por exemplo, você pode remover um cluster se a descoberta de cluster falhar ou quando quiser desativar um sistema de storage.

*O que você vai precisar*

Você deve ter a função Administrador do aplicativo ou a função Administrador do armazenamento.

Esta tarefa remove o cluster selecionado do Unified Manager. Depois que um cluster é removido, ele não é mais monitorado. A instância do Unified Manager registrada com o cluster removido também não é registrada do cluster.

A remoção de um cluster também exclui todos os objetos de armazenamento, dados históricos, serviços de armazenamento e todos os eventos associados do Unified Manager. Essas alterações são refletidas nas páginas de inventário e nas páginas de detalhes após o próximo ciclo de coleta de dados.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração do cluster*.
. Na página Configuração do cluster, selecione o cluster que deseja remover e clique em *Remover*.
. Na caixa de diálogo *Remover fonte de dados*, clique em *Remover* para confirmar a solicitação de remoção.


*Informações relacionadas*

link:../config/task_add_users.html["Adicionando usuários"]

link:../health-checker/task_view_cluster_list_and_details.html["Visualizar a lista de cluster e os detalhes"]
