---
permalink: storage-mgmt/task_remove_vcenter_server.html 
sidebar: sidebar 
keywords: review, vcenter, server 
summary: Você pode remover o vCenter Servers de sua instância do Active IQ Unified Manager quando ela não for mais necessária. 
---
= Remover o vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover o vCenter Servers da sua instância do Active IQ Unified Manager. Por exemplo, você pode remover um vCenter Server se a descoberta do vCenter Server falhar ou quando ela não for mais necessária.

A remoção de um vCenter Server também exclui todas as máquinas virtuais (VMs) hospedadas nesse vCenter e seus dados de configuração. Depois que o vCenter Server for removido, ele não será mais monitorado, juntamente com seus objetos associados e dados históricos. Essas alterações serão refletidas nas páginas de inventário do vCenter e da máquina virtual.

.Antes de começar
Antes de remover o vCenter Servers, verifique o seguinte:

* Você tem a função Administrador de aplicativos ou a função Administrador de armazenamento.
* Você deve estar ciente dos nomes do vCenter Server e respetivos endereços IP associados a eles.


.Passos
. No painel de navegação à esquerda, clique em *VMware>vCenter*.
. Na página vCenters, selecione o vCenter Server que deseja remover e clique em *Remover*.
. Na caixa de diálogo *Remover vCenter*, clique em *OK* para confirmar a solicitação de remoção.

