---
permalink: storage-mgmt/task_edit_user_and_group_quota_email_addresses.html 
sidebar: sidebar 
keywords: edit, user, group, quota, email, addresses 
summary: 'É possível modificar os endereços de e-mail com base na cota de usuário associada a clusters, máquinas virtuais de armazenamento (SVMs), volumes, qtrees, usuários ou grupos de usuários. Você pode modificar o endereço de e-mail quando quiser substituir o endereço de e-mail gerado pelas regras especificadas na caixa de diálogo regras para gerar Endereço de e-mail de cota de usuário e grupo.' 
---
= Editando endereços de e-mail de cota de usuário e grupo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível modificar os endereços de e-mail com base na cota de usuário associada a clusters, máquinas virtuais de armazenamento (SVMs), volumes, qtrees, usuários ou grupos de usuários. Você pode modificar o endereço de e-mail quando quiser substituir o endereço de e-mail gerado pelas regras especificadas na caixa de diálogo regras para gerar Endereço de e-mail de cota de usuário e grupo.

*O que você vai precisar*

* Tem de ter a função Operador, Administrador de aplicações ou Administrador de armazenamento.
* Tem de ter revisto a link:reference_rules_to_generate_user_and_group_quota.html["diretrizes para a criação de regras"].


Se você editar um endereço de e-mail, as regras para gerar os endereços de e-mail de cota de usuário e grupo não serão mais aplicáveis à cota. Para que as notificações sejam enviadas para o endereço de e-mail gerado pelas regras especificadas, você deve excluir o endereço de e-mail e salvar a alteração.

.Passos
. No painel de navegação esquerdo, clique em *Storage* > *SVMs*.
. Na exibição *Saúde: Todas as VMs de armazenamento*, selecione um SVM e clique na guia *cotas de usuário e grupo*.
. Clique em *Editar endereço de e-mail* abaixo da linha de guias.
. Na caixa de diálogo *Editar endereço de e-mail*, execute a ação apropriada:
+
|===
| Se... | Então... 


 a| 
Você deseja que as notificações sejam enviadas para o endereço de e-mail gerado pelas regras especificadas
 a| 
.. Exclua o endereço de e-mail no campo *Endereço de e-mail*.
.. Clique em *Salvar*.
.. Atualize o navegador pressionando F5 para recarregar a caixa de diálogo Editar endereço de e-mail. O endereço de e-mail gerado pela regra especificada é exibido no campo *Endereço de e-mail*.




 a| 
Você deseja que as notificações sejam enviadas para um endereço de e-mail especificado
 a| 
.. Modifique o endereço de e-mail no campo *Endereço de e-mail*.
.. Clique em *Salvar*. As regras para gerar os endereços de e-mail de cota de usuário e grupo não são mais aplicáveis à cota.


|===

