---
permalink: storage-mgmt/task_create_and_edit_seps.html 
sidebar: sidebar 
keywords: create, edit, storage, efficiency, policies 
summary: Quando as políticas de eficiência de storage definidas pelo sistema não correspondem aos requisitos de workload, você pode criar suas próprias políticas de eficiência de storage otimizadas para seus workloads. 
---
= Criação e edição de políticas de eficiência de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando as políticas de eficiência de storage definidas pelo sistema não correspondem aos requisitos de workload, você pode criar suas próprias políticas de eficiência de storage otimizadas para seus workloads.

*O que você vai precisar*

* Tem de ter a função Administrador de aplicações.
* O nome da Política de eficiência de armazenamento deve ser exclusivo e você não pode usar as seguintes palavras-chave reservadas:
+
`High` `Low`, , `Unassigned` `Learning` , `Idle`, , , `Default`, e `None`.



Você cria e edita políticas de eficiência de storage personalizadas na página políticas de eficiência de storage definindo as características de eficiência de storage necessárias para os aplicativos que acessarão o storage.

[NOTE]
====
Não é possível modificar uma Política de eficiência de storage se ela estiver atualmente atribuída a uma carga de trabalho.

====
.Passos
. No painel de navegação à esquerda em *Settings*, selecione *Policies* > *Storage Efficiency*.
. Na página *políticas de eficiência de armazenamento*, clique no botão apropriado, dependendo se você deseja criar uma nova Política de eficiência de armazenamento ou se deseja editar uma Política de eficiência de armazenamento existente.
+
|===
| Para... | Siga estes passos... 


 a| 
Crie uma nova política de eficiência de storage
 a| 
Clique em *Add*



 a| 
Editar uma política de eficiência de storage existente
 a| 
Selecione uma Política de eficiência de armazenamento existente e clique em *Editar*

|===
+
A página para adicionar ou editar uma Política de eficiência de armazenamento é exibida.

. Personalize a Política de eficiência de armazenamento especificando as caraterísticas de eficiência de armazenamento e clique em *Enviar* para salvar a Política de eficiência de armazenamento.


Você pode aplicar a nova ou alterada Política de eficiência de storage a workloads (LUNs, compartilhamentos de arquivos NFS, compartilhamentos CIFS) da página de workloads ou ao provisionar um novo workload.
