---
permalink: health-checker/concept_configure_backup_for_windows.html 
sidebar: sidebar 
keywords: backup, restore, windows, netapp, snapshot copy, copies, configure, backup 
summary: O Active IQ Unified Manager suporta backup e restauração usando snapshots NetApp no sistema operacional Windows com a ajuda de LUN usando protocolo iSCSI. 
---
= Configurando backup no Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Active IQ Unified Manager suporta backup e restauração usando snapshots NetApp no sistema operacional Windows com a ajuda de LUN usando protocolo iSCSI.

O backup baseado em snapshot pode ser feito enquanto todos os serviços do Unified Manager estão em execução. Um estado consistente do banco de dados é capturado como parte do Snapshot, pois o backup coloca um bloqueio de leitura global em todo o banco de dados, o que impede qualquer gravação simultânea. Para que o sistema Unified Manager instalado no sistema operacional Windows execute backup e restauração usando snapshots do NetApp, primeiro você deve configurar o backup do Unified Manager para Snapshot com base no console de manutenção.

Antes de configurar o Unified Manager para a criação de cópias Snapshot, execute as seguintes tarefas de configuração.

* Configurar cluster ONTAP
* Configurar a máquina host do Windows

