---
permalink: health-checker/concept_configure_backup_for_linux.html 
sidebar: sidebar 
keywords: netapp, snapshot copy, copies, linux, operate, system, configure, backup 
summary: Se o Active IQ Unified Manager estiver instalado em uma máquina Linux, você poderá decidir configurar o backup e a restauração usando os snapshots do NetApp. 
---
= Configure backup no Linux no Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o Active IQ Unified Manager estiver instalado em uma máquina Linux, você poderá decidir configurar o backup e a restauração usando os snapshots do NetApp.

As cópias snapshot demoram muito pouco tempo, geralmente apenas alguns minutos, e o banco de dados do Unified Manager fica bloqueado por um período de tempo muito curto, portanto, há muito pouca interrupção na instalação. A imagem consome espaço de armazenamento mínimo e incorre em sobrecarga de desempenho insignificante, pois Registra apenas alterações nos arquivos desde que a última cópia Snapshot foi feita. Como o Snapshot é criado em um cluster do ONTAP, você pode aproveitar outros recursos do NetApp, como o SnapMirror, para criar proteção secundária, se necessário.

Antes de iniciar uma operação de backup, o Unified Manager realiza uma verificação de integridade para verificar se o sistema de destino está disponível.

[NOTE]
====
* Você pode restaurar uma cópia Snapshot somente na mesma versão do Active IQ Unified Manager.
+
Por exemplo, se você criou um backup no Unified Manager 9.18, o backup poderá ser restaurado somente em sistemas Unified Manager 9.18.

* Se houver alguma alteração na configuração Snapshot, isso pode fazer com que o snapshot seja inválido.


====


[[configure-snapshot-copy-location-in-active-iq-unified-manager]]
== Configure o local da cópia Snapshot no Active IQ Unified Manager

Você pode configurar o volume no qual as cópias Snapshot serão armazenadas em um dos clusters do ONTAP usando o Gerenciador de sistemas do ONTAP ou a CLI do ONTAP.

.Antes de começar
O cluster, a VM de storage e o volume devem atender aos seguintes requisitos:

* Requisitos do cluster:
+
** O ONTAP 9 .3 ou superior deve ser instalado
** Ele deve estar geograficamente perto do servidor do Unified Manager
** Ele pode ser monitorado pelo Unified Manager, mas não é necessário


* Requisitos da VM de storage:
+
** A chave de nome e o mapeamento de nomes devem ser definidos para usar "'arquivos'"
** Usuários locais criados para corresponder aos usuários do lado do cliente
** Certifique-se de que todos os acessos de leitura/escrita estão selecionados
** Certifique-se de que o acesso ao superusuário está definido como "'any'" na política de exportação
** NFS para NetApp Snapshot para Linux
** O NFSv4 deve estar ativado no servidor NFS e no domínio de ID NFSv4 especificado no cliente e na VM de armazenamento
** O volume deve ser pelo menos o dobro do tamanho do diretório Unified Manager/opt/NetApp/data
+
Use o comando du -sh /opt/NetApp/data/ para verificar o tamanho atual.



* Requisitos de volume:
+
** O volume deve ser pelo menos o dobro do tamanho do diretório /opt/NetApp/data do Unified Manager
** O estilo de segurança deve ser definido como UNIX
** A política de instantâneos locais tem de ser desativada
** O dimensionamento automático do volume deve estar ativado
** O nível de serviço de desempenho deve ser definido para uma política com IOPS alto e baixa latência, como o "Extreme"




Para obter as etapas detalhadas para criar o volume NFS, consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_NFSv4_in_Cluster-Mode["Como configurar o NFSv4 no ONTAP 9"] e o http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-nfsv3-cg/home.html["Guia expresso de configuração de NFS do ONTAP 9"].



[[specify-the-destination-location-for-snapshot-copies-in-active-iq-unified-manager]]
== Especifique o local de destino para as cópias Snapshot no Active IQ Unified Manager

Você deve configurar o local de destino para cópias Snapshot do Active IQ Unified Manager em um volume que já tenha configurado em um de seus clusters do ONTAP. Você deve usar o console de manutenção para definir a localização.

* Você deve ter as credenciais de usuário raiz para o host Linux no qual o Active IQ Unified Manager está instalado.
* Você deve ter uma ID de usuário e senha autorizados para fazer login no console de manutenção do servidor do Unified Manager.
* Você deve ter o endereço IP de gerenciamento de cluster, o nome da VM de armazenamento, o nome do volume e o nome de usuário e senha do sistema de armazenamento.
* Você deve ter montado o volume no host Active IQ Unified Manager e deve ter o caminho de montagem.


.Passos
. Use Shell seguro para se conetar ao endereço IP ou FQDN do sistema Active IQ Unified Manager.
. Inicie sessão no sistema com o nome e a palavra-passe do utilizador de manutenção (umadmin).
. Digite o comando `maintenance_console` e pressione Enter.
. No console de manutenção *Menu Principal*, digite o número da opção *Backup Restore*.
. Digite o número para *Configurar cópia de segurança de instantâneo do NetApp*.
. Introduza o número para configurar o NFS.
. Revise as informações que você precisará fornecer e insira o número de *Digite os detalhes da configuração de backup*.
. Para identificar o volume em que o instantâneo será gravado, insira o endereço IP da interface de gerenciamento de cluster, o nome da VM de armazenamento, o nome do volume, o nome do LUN, o nome do usuário e a senha do sistema de armazenamento e o caminho de montagem.
. Verifique essas informações e `y` digite .
+
O sistema executa as seguintes tarefas:

+
** Estabelece a conexão com o cluster
** Pára todos os serviços
** Cria um novo diretório no volume e copia os arquivos de configuração do banco de dados Active IQ Unified Manager
** Exclui os arquivos do Active IQ Unified Manager e cria um link simbólico para o novo diretório de banco de dados
** Reinicia todos os serviços


. Saia do console de manutenção e inicie a interface do Active IQ Unified Manager para criar um agendamento para a cópia Snapshot se você ainda não tiver feito isso.

