---
permalink: health-checker/task_configure_global_aggregate_health_threshold_values.html 
sidebar: sidebar 
keywords: configure, global, aggregate, health, threshold values 
summary: Você pode configurar valores de limite de integridade globais para todos os agregados para rastrear qualquer violação de limite. Eventos apropriados são gerados para violações de limites e você pode tomar medidas preventivas com base nesses eventos. Você pode configurar os valores globais com base nas configurações de práticas recomendadas para limites que se aplicam a todos os agregados monitorados. 
---
= Configurando valores de limite globais de integridade agregada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar valores de limite de integridade globais para todos os agregados para rastrear qualquer violação de limite. Eventos apropriados são gerados para violações de limites e você pode tomar medidas preventivas com base nesses eventos. Você pode configurar os valores globais com base nas configurações de práticas recomendadas para limites que se aplicam a todos os agregados monitorados.

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

Quando você configura as opções globalmente, os valores padrão dos objetos são modificados. No entanto, se os valores padrão tiverem sido alterados no nível do objeto, os valores globais não serão modificados.

As opções de limite têm valores padrão para melhor monitoramento, no entanto, você pode alterar os valores de acordo com os requisitos do seu ambiente.

Quando o crescimento automático é ativado em volumes que residem no agregado, os limites de capacidade agregada são considerados violados com base no tamanho máximo do volume definido pelo crescimento automático, não com base no tamanho do volume original.

[NOTE]
====
Os valores de limite de integridade não são aplicáveis ao agregado raiz do nó.

====
.Passos
. No painel de navegação à esquerda, clique em *limiares de eventos* > *agregado*.
. Configurar os valores-limite apropriados para capacidade, crescimento e cópias Snapshot.
. Clique em *Salvar*.


*Informações relacionadas*

link:../config/task_add_users.html["Adicionando usuários"]
