---
permalink: health-checker/task_view_list_of_snapshot_copies.html 
sidebar: sidebar 
keywords: view, list, Snapshot copies 
summary: É possível exibir a lista de cópias Snapshot de um volume selecionado. Você pode usar a lista de cópias Snapshot para calcular a quantidade de espaço em disco que pode ser recuperado se uma ou mais cópias Snapshot forem excluídas e excluir as cópias Snapshot, se necessário. 
---
= Exibição da lista de cópias Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível exibir a lista de cópias Snapshot de um volume selecionado. Você pode usar a lista de cópias Snapshot para calcular a quantidade de espaço em disco que pode ser recuperado se uma ou mais cópias Snapshot forem excluídas e excluir as cópias Snapshot, se necessário.

*O que você vai precisar*

* Tem de ter a função Operador, Administrador de aplicações ou Administrador de armazenamento.
* O volume que contém as cópias Snapshot precisa estar online.


.Passos
. No painel de navegação esquerdo, clique em *Storage* > *volumes*.
. Na exibição *Saúde: Todos os volumes*, selecione o volume que contém as cópias Snapshot que deseja exibir.
. Na página de detalhes *volume / Saúde*, clique na guia *capacidade*.
. No painel *Detalhes* da guia *capacidade*, na seção outros detalhes, clique no link ao lado de *cópias instantâneas*.
+
O número de cópias Snapshot é um link que exibe a lista de cópias snapshot.



*Informações relacionadas*

link:../health-checker/reference_health_volume_details_page.html["Página de integridade/volumes"]
