---
permalink: health-checker/task_edit_individual_qtree_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, qtree, health, threshold, settings 
summary: Você pode editar as configurações de limite de integridade para a capacidade de qtree para um ou mais qtrees. Quando um limite é cruzado, os alertas são gerados e você recebe notificações. Essas notificações ajudam você a tomar medidas preventivas com base no evento gerado. 
---
= Editar configurações individuais de limite de integridade de qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar as configurações de limite de integridade para a capacidade de qtree para um ou mais qtrees. Quando um limite é cruzado, os alertas são gerados e você recebe notificações. Essas notificações ajudam você a tomar medidas preventivas com base no evento gerado.

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

Com base nas alterações nos valores de limite, os eventos são gerados ou obsoletos no próximo ciclo de monitoramento.

.Passos
. No painel de navegação esquerdo, clique em *Storage* > *Qtrees*.
. Na visualização *Capacity: All Qtrees*, selecione um ou mais qtrees e clique em *Edit thresholds*.
. Na caixa de diálogo *Editar limites de Qtree*, altere os limites de capacidade para a qtree ou qtrees selecionados e clique em *Salvar*.
+
[NOTE]
====
Você também pode definir limites de qtree individuais na guia Qtrees na página Storage VM / Health details.

====

