---
permalink: health-checker/task_configure_global_volume_health_threshold_values.html 
sidebar: sidebar 
keywords: configure, global, volume, health, threshold values 
summary: Você pode configurar os valores de limite de integridade global para todos os volumes para rastrear qualquer violação de limite. Eventos apropriados são gerados para violações de limites de integridade e você pode tomar medidas preventivas com base nesses eventos. Você pode configurar os valores globais com base nas configurações de práticas recomendadas para limites que se aplicam a todos os volumes monitorados. 
---
= Configuração dos valores do limite de integridade do volume global
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar os valores de limite de integridade global para todos os volumes para rastrear qualquer violação de limite. Eventos apropriados são gerados para violações de limites de integridade e você pode tomar medidas preventivas com base nesses eventos. Você pode configurar os valores globais com base nas configurações de práticas recomendadas para limites que se aplicam a todos os volumes monitorados.

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

A maioria das opções de limite tem valores padrão para melhor monitoramento. No entanto, você pode alterar os valores de acordo com os requisitos do seu ambiente.

Observe que, quando o crescimento automático está ativado em um volume, os limites de capacidade são considerados violados com base no tamanho máximo do volume definido pelo crescimento automático, não com base no tamanho do volume original.

[NOTE]
====
O valor padrão de 1000 cópias Snapshot é aplicável somente a volumes FlexVol quando a versão do ONTAP é 9,4 ou superior e a volumes FlexGroup quando a versão do ONTAP é 9,8 ou superior. Para clusters instalados com versões mais antigas do software ONTAP, o número máximo é de 250 cópias de Snapshot por volume. Para essas versões mais antigas, o Unified Manager interpreta esse número 1000 (e qualquer número entre 1000 e 250) como 250; o que significa que você continuará recebendo eventos quando o número de cópias Snapshot chegar a 250. Se você deseja definir esse limite para menos de 250 para essas versões mais antigas, você deve definir o limite para 250 ou mais baixo aqui, na exibição Saúde: Todos os volumes ou na página Detalhes volume / Saúde.

====
.Passos
. No painel de navegação esquerdo, clique em *limiares de eventos* > *volume*.
. Configurar os valores de limite apropriados para capacidade, cópias Snapshot, cotas de qtree, crescimento de volume e inodes.
. Clique em *Salvar*.


*Informações relacionadas*

link:../config/task_add_users.html["Adicionando usuários"]
