---
permalink: health-checker/task_view_security_events_that_require_software_or_firmware_updates.html 
sidebar: sidebar 
keywords: upgrade events, view, security events, software, firmware updates 
summary: 'Existem certos eventos de segurança que têm uma área de impactos de "Atualização". Esses eventos são relatados da plataforma Active IQ e identificam problemas em que a resolução exige que você atualize o software ONTAP, o firmware do nó ou o software do sistema operacional (para avisos de segurança).' 
---
= Exibição de eventos de segurança que podem exigir atualizações de software ou firmware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem certos eventos de segurança que têm uma área de impactos do "Upgrade". Esses eventos são relatados da plataforma Active IQ e identificam problemas em que a resolução exige que você atualize o software ONTAP, o firmware do nó ou o software do sistema operacional (para avisos de segurança).

*O que você vai precisar*

Tem de ter a função Operador, Administrador de aplicações ou Administrador de armazenamento.

Você pode querer executar ações corretivas imediatas para alguns desses problemas, enquanto outros problemas podem esperar até a próxima manutenção programada. Você pode visualizar todos esses eventos e atribuí-los a usuários que podem resolver os problemas. Além disso, se houver certos eventos de atualização de segurança sobre os quais você não deseja ser notificado, esta lista pode ajudá-lo a identificar esses eventos para que você possa desativá-los.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de eventos*.
+
Por padrão, todos os eventos ativos (novos e confirmados) são exibidos na página de inventário do Gerenciamento de Eventos.

. No menu Exibir, selecione *Atualizar eventos*.
+
A página exibe todos os eventos de segurança de atualização ativos.


