---
permalink: health-checker/task_add_alerts_for_security_events.html 
sidebar: sidebar 
keywords: add, alerts, security events 
summary: Você pode configurar alertas para eventos de segurança individuais, como qualquer outro evento recebido pelo Unified Manager. Além disso, se você quiser tratar todos os eventos de segurança da mesma forma e mandar e-mails para a mesma pessoa, você pode criar um único alerta para notificá-lo quando quaisquer eventos de segurança forem acionados. 
---
= Adicionar alertas para eventos de segurança
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar alertas para eventos de segurança individuais, como qualquer outro evento recebido pelo Unified Manager. Além disso, se você quiser tratar todos os eventos de segurança da mesma forma e mandar e-mails para a mesma pessoa, você pode criar um único alerta para notificá-lo quando quaisquer eventos de segurança forem acionados.

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

O exemplo abaixo mostra como criar um alerta para o evento de segurança ""Protocolo Telnet ativado"". Isso enviará um alerta se o acesso Telnet estiver configurado para acesso administrativo remoto ao cluster. Você pode usar essa mesma metodologia para criar alertas para todos os eventos de segurança.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de alerta*.
. Na página *Configuração de alerta*, clique em *Adicionar*.
. Na caixa de diálogo *Adicionar alerta*, clique em *Nome* e insira um nome e uma descrição para o alerta.
. Clique em *recursos* e selecione o cluster ou cluster no qual deseja ativar esse alerta.
. Clique em *Eventos* e execute as seguintes ações:
+
.. Na lista gravidade do evento, selecione *Aviso*.
.. Na lista Eventos correspondentes, selecione *Protocolo Telnet ativado*.


. Clique em *ações* e selecione o nome do usuário que receberá o e-mail de alerta no campo *alertar esses usuários*.
. Configure quaisquer outras opções nesta página para frequência de notificação, emissão de toques SNMP e execução de um script.
. Clique em *Salvar*.

