---
permalink: health-checker/task_edit_individual_volume_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, volume, health, threshold, settings 
summary: Você pode editar as configurações de limite de integridade para capacidade de volume, crescimento, cota e reserva de espaço de um ou mais volumes. Quando um limite é cruzado, os alertas são gerados e você recebe notificações. Essas notificações ajudam você a tomar medidas preventivas com base no evento gerado. 
---
= Editar definições individuais de limite de integridade do volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar as configurações de limite de integridade para capacidade de volume, crescimento, cota e reserva de espaço de um ou mais volumes. Quando um limite é cruzado, os alertas são gerados e você recebe notificações. Essas notificações ajudam você a tomar medidas preventivas com base no evento gerado.

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

Com base nas alterações nos valores de limite, os eventos são gerados ou obsoletos no próximo ciclo de monitoramento.

Observe que, quando o crescimento automático está ativado em um volume, os limites de capacidade são considerados violados com base no tamanho máximo do volume definido pelo crescimento automático, não com base no tamanho do volume original.

[NOTE]
====
O valor padrão de 1000 cópias Snapshot é aplicável somente a volumes FlexVol quando a versão do ONTAP é 9,4 ou superior e a volumes FlexGroup quando a versão do ONTAP é 9,8 ou superior. Para clusters instalados com versões mais antigas do software ONTAP, o número máximo é de 250 cópias de Snapshot por volume. Para essas versões mais antigas, o Unified Manager interpreta esse número 1000 (e qualquer número entre 1000 e 250) como 250; o que significa que você continuará recebendo eventos quando o número de cópias Snapshot chegar a 250. Se você deseja definir esse limite para menos de 250 para essas versões mais antigas, você deve definir o limite para 250 ou mais baixo aqui, na exibição Saúde: Todos os volumes ou na página Detalhes volume / Saúde.

====
.Passos
. No painel de navegação esquerdo, clique em *Storage* > *volumes*.
. Na exibição *Saúde: Todos os volumes*, selecione um ou mais volumes e clique em *Editar limites*.
. Na caixa de diálogo *Editar limites de volume*, edite as configurações de limite de uma das seguintes opções: Capacidade, cópias Snapshot, cota de qtree, crescimento ou inodes selecionando a caixa de seleção apropriada e modificando as configurações.
. Clique em *Salvar*.


*Informações relacionadas*

link:../config/task_add_users.html["Adicionando usuários"]
