---
permalink: health-checker/task_view_all_security_events.html 
sidebar: sidebar 
keywords: view, active, security events 
summary: Você pode exibir todos os eventos de segurança ativos e, em seguida, atribuir cada um deles a um usuário que pode resolver o problema. Além disso, se houver certos eventos de segurança que você não deseja receber, esta lista pode ajudá-lo a identificar os eventos que deseja desativar. 
---
= Visualizar todos os eventos de segurança ativos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir todos os eventos de segurança ativos e, em seguida, atribuir cada um deles a um usuário que pode resolver o problema. Além disso, se houver certos eventos de segurança que você não deseja receber, esta lista pode ajudá-lo a identificar os eventos que deseja desativar.

*O que você vai precisar*

Tem de ter a função Operador, Administrador de aplicações ou Administrador de armazenamento.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de eventos*.
+
Por padrão, eventos novos e confirmados são exibidos na página de inventário do Gerenciamento de Eventos.

. No menu Exibir, selecione *Eventos de segurança ativos*.
+
A página exibe todos os eventos de Segurança novos e reconhecidos que foram gerados nos últimos 7 dias.


