---
permalink: health-checker/task_view_node_list_and_details.html 
sidebar: sidebar 
keywords: view, node list, details 
summary: 'Você pode usar a visualização integridade: Todos os nós para exibir a lista de nós nos clusters. Você pode usar a página de detalhes de Cluster / Health para exibir informações detalhadas sobre nós que fazem parte do cluster monitorado.' 
---
= Exibindo a lista de nós e os detalhes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a visualização integridade: Todos os nós para exibir a lista de nós nos clusters. Você pode usar a página de detalhes de Cluster / Health para exibir informações detalhadas sobre nós que fazem parte do cluster monitorado.

*O que você vai precisar*

Tem de ter a função Operador, Administrador de aplicações ou Administrador de armazenamento.

Você pode visualizar detalhes como o estado do nó, o cluster que contém o nó, os detalhes de capacidade agregada (usada e total) e os detalhes de capacidade bruta (utilizável, sobressalente e total). Você também pode obter informações sobre pares de HA, compartimentos de discos e portas.

.Passos
. No painel de navegação esquerdo, clique em *Storage* > *Nodes*.
. Na exibição *Saúde: Todos os nós*, clique no nó cujos detalhes você deseja exibir.
+
As informações detalhadas para o nó selecionado são apresentadas na página Cluster / Health details (Detalhes do Cluster/Health). O painel esquerdo exibe a lista de pares de HA. Por padrão, os Detalhes da HA estão abertos, que exibe detalhes do estado da HA e eventos relacionados ao par de HA selecionado.

. Para exibir outros detalhes sobre o nó, execute a ação apropriada:
+
[cols="2*"]
|===
| Para ver... | Clique em... 


 a| 
Detalhes sobre as gavetas de disco
 a| 
*Prateleiras de disco*.



 a| 
Informações relacionadas com a porta
 a| 
*Portos*.

|===


Para obter mais informações, consulte:

* link:../performance-checker/performance-view-all.html#performance-all-nodes-view["Performance: Visualização de todos os nós"]
* link:../performance-checker/concept_view_node_and_aggregate_available_iops_values.html["Exibindo o nó e agregar valores de IOPS disponíveis"]
* link:../performance-checker/concept_view_node_and_aggregate_performance_capacity_used_values.html["Exibindo valores de capacidade de desempenho agregado e nó usados"]

