---
permalink: health-checker/task_add_values_to_annotations.html 
sidebar: sidebar 
keywords: add, values, annotations 
summary: Você pode adicionar valores a anotações e, em seguida, associar objetos de armazenamento a um par de nome-valor de anotação específico. Adicionar valores a anotações ajuda a gerenciar objetos de armazenamento de forma mais eficaz. 
---
= Adicionar valores a anotações
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar valores a anotações e, em seguida, associar objetos de armazenamento a um par de nome-valor de anotação específico. Adicionar valores a anotações ajuda a gerenciar objetos de armazenamento de forma mais eficaz.

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

Não é possível adicionar valores a anotações predefinidas.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Anotações*.
. Na página *Anotações*, selecione a anotação à qual deseja adicionar um valor e clique em *Add* na seção *values*.
. Na caixa de diálogo *Add Annotation value* (Adicionar valor de anotação), especifique um valor para a anotação.
+
O valor que especificar tem de ser exclusivo para a anotação selecionada.

. Clique em *Add*.

