---
permalink: health-checker/task_migrate_um_virtual_appliance_to_rhel_or_centos_system.html 
sidebar: sidebar 
keywords: unified manager, migrate, virtual, appliance, linux system 
summary: É possível restaurar um backup de despejo de banco de dados MySQL do Unified Manager de um dispositivo virtual para um sistema Red Hat Enterprise Linux ou CentOS Linux se quiser alterar o sistema operacional de host no qual o Unified Manager está sendo executado. 
---
= Migração de um dispositivo virtual do Unified Manager para um sistema Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível restaurar um backup de despejo de banco de dados MySQL do Unified Manager de um dispositivo virtual para um sistema Red Hat Enterprise Linux ou CentOS Linux se quiser alterar o sistema operacional de host no qual o Unified Manager está sendo executado.

*O que você vai precisar*

* No dispositivo virtual:
+
** Tem de ter a função Operador, Administrador de aplicações ou Administrador de armazenamento.
** Você deve saber o nome do usuário de manutenção do Unified Manager para a operação de restauração.


* No sistema Linux:
+
** Você deve ter instalado o Unified Manager em um servidor Linux seguindo as instruções no link:../install-linux/concept_install_unified_manager_on_rhel_or_centos.html["Instalar o Unified Manager em sistemas Linux"].
** A versão do Unified Manager neste servidor deve ser a mesma do dispositivo virtual a partir do qual você está usando o arquivo de backup.
** Não inicie a IU nem configure clusters, usuários ou configurações de autenticação no sistema Linux após a instalação. O arquivo de backup preenche essas informações durante o processo de restauração.
** Você deve ter as credenciais de usuário raiz para o host Linux.




Estas etapas descrevem como criar um arquivo de backup no dispositivo virtual, copiar os arquivos de backup para o sistema Red Hat Enterprise Linux ou CentOS e restaurar o backup do banco de dados para o novo sistema.

.Passos
. No dispositivo virtual, clique em *Management* > *Database Backup*.
. Na página *Backup do banco de dados*, clique em *Backup Settings*.
. Altere o caminho de backup para /jail/support.
. Na seção Agendamento, selecione *programado diariamente* e insira um tempo depois da hora atual para que o backup seja criado em breve.
. Clique em *aplicar*.
. Aguarde algumas horas para que o backup seja gerado.
+
Um backup completo pode ter mais de 1 GB e pode levar de três a quatro horas para ser concluído.

. Faça login como o usuário raiz no host Linux no qual o Unified Manager está instalado e copie os arquivos de backup de /support no dispositivo virtual usando SCP.`root@<rhel_server>:/# scp -r admin@<vapp_server_ip_address>:/support/* .`
+
`root@ocum_rhel-21:/# scp -r admin@10.10.10.10:/support/* .`

+
Certifique-se de ter copiado o arquivo de backup .7z e todos os arquivos de repositório .7z no subdiretório /database-dumps-repo.

. No prompt de comando, restaure o backup: `um backup restore -f /<backup_file_path>/<backup_file_name>`
+
`um backup restore -f /UM_9.7.N151113.1348_backup_unix_02-12-2019-04-16.7z`

. Após a conclusão da operação de restauração, faça login na IU da Web do Unified Manager.


Você deve executar as seguintes tarefas:

* Gere um novo certificado de segurança HTTPS e reinicie o servidor do Unified Manager.
* Altere o caminho de backup para a configuração padrão do seu sistema Linux (/data/ocum-backup), ou para um novo caminho de sua escolha, porque não há nenhum caminho /jail/support no sistema Linux.
* Reconfigure ambos os lados da conexão do Workflow Automation, se O WFA estiver sendo usado.
* Reconfigure as configurações de autenticação SAML, se você estiver usando SAML.


Depois de verificar se tudo está sendo executado como esperado no sistema Linux, você pode desligar e remover o dispositivo virtual do Unified Manager.
