---
permalink: install-vapp/task_upgrade_unified_manager_vapp.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Você pode fazer o upgrade para o Unified Manager no VMware vSphere 
---
= Atualizar o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar o Active IQ Unified Manager para a versão 9,16 apenas a partir da versão 9,13 ou 9,14.

Durante o processo de atualização, o Unified Manager não está disponível. Você deve concluir todas as operações em execução antes de atualizar o Unified Manager.

Se o Unified Manager estiver emparelhado com uma instância do OnCommand Workflow Automation e houver novas versões de software disponíveis para ambos os produtos, será necessário desconetar os dois produtos e configurar uma nova conexão do Workflow Automation após a realização das atualizações. Se você estiver executando uma atualização para apenas um dos produtos, deverá fazer login no Workflow Automation após a atualização e verificar se ele ainda está adquirindo dados do Unified Manager.

.Passos
. Siga as etapas em link:task_download_unified_manager_iso_image_vapp.html["Faça o download da imagem ISO do Unified Manager"].
. Além disso, siga as etapas descritas em link:task_upgrade_unified_manager_virtual_appliance_vapp.html["Atualizar o Unified Manager"].

