---
permalink: install-windows/reference_protocol_and_port_requirements.html 
sidebar: sidebar 
keywords: unified manager, protocol, port, requirements 
summary: As portas e protocolos necessários permitem a comunicação entre o servidor do Unified Manager e os sistemas de storage gerenciado, servidores e outros componentes. 
---
= Requisitos de protocolo e porta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As portas e protocolos necessários permitem a comunicação entre o servidor do Unified Manager e os sistemas de storage gerenciado, servidores e outros componentes.



== Conexões ao servidor do Unified Manager

Em instalações típicas, você não precisa especificar números de porta ao se conetar à IU da Web do Unified Manager, porque as portas padrão são sempre usadas. Por exemplo, como o Unified Manager sempre tenta executar em sua porta padrão, você pode digitar `+https://<host>+` em vez `+https://<host>:443+` de .

O servidor do Unified Manager usa protocolos específicos para acessar as seguintes interfaces:

[cols="4*"]
|===
| Interface | Protocolo | Porta | Descrição 


 a| 
IU da Web do Unified Manager
 a| 
HTTP
 a| 
80
 a| 
Usado para acessar a IU da Web do Unified Manager; redireciona automaticamente para a porta segura 443.



 a| 
IU da Web do Unified Manager e programas que usam APIs
 a| 
HTTPS
 a| 
443
 a| 
Usado para acessar com segurança a IU da Web do Unified Manager ou para fazer chamadas de API; as chamadas de API só podem ser feitas usando HTTPS.



 a| 
Consola de manutenção
 a| 
SSH/SFTP
 a| 
22
 a| 
Usado para acessar o console de manutenção e recuperar pacotes de suporte.



 a| 
Linha de comando Linux
 a| 
SSH/SFTP
 a| 
22
 a| 
Usado para acessar a linha de comando Red Hat Enterprise Linux e recuperar pacotes de suporte.



 a| 
Syslog
 a| 
UDP
 a| 
514
 a| 
Utilizado para aceder a mensagens EMS baseadas em subscrição a partir de sistemas ONTAP e para criar eventos com base nas mensagens.



 a| 
DESCANSO
 a| 
HTTPS
 a| 
9443
 a| 
Usado para acessar eventos EMS baseados em API REST em tempo real a partir de sistemas ONTAP autenticados.



 a| 
Banco de dados MySQL
 a| 
MySQL
 a| 
3306
 a| 
Usado para habilitar o acesso aos Serviços de API do OnCommand Workflow Automation e do OnCommand ao Unified Manager.



 a| 
AMQP QPID broker
 a| 
TCP/IP
 a| 
56072
 a| 
Usado para comunicação de mensagens internas.



 a| 
AMQP QPID broker
 a| 
WebSocket sobre TCP
 a| 
56080
 a| 
Usado para ouvir nessa porta as mensagens recebidas do ONTAP (agente de nuvem).



 a| 
AMQP QPID broker
 a| 
WebSocket sobre TCP
 a| 
56443
 a| 
Usado para ouvir nessa porta as mensagens recebidas do ONTAP (agente em nuvem). A comunicação por essa porta suporta criptografia fornecida pelo TLS ou SSL.

|===
[NOTE]
====
A porta padrão para MySQL, 3306, é restrita apenas ao localhost durante a instalação do Unified Manager em sistemas Windows. Ative o firewall para restringir o acesso à porta MySQL, 3306, uma vez concluída a instalação. Isso não afeta nenhum cenário de atualização, onde a configuração anterior é mantida. Esta configuração pode ser modificada e a conexão pode ser disponibilizada a outros hosts usando a `Control access to MySQL port 3306` opção no console de manutenção. Para obter informações, link:../config/reference_additional_menu_options.html["Opções de menu adicionais"]consulte . As portas usadas para comunicação HTTP e HTTPS (portas 80 e 443) podem ser alteradas usando o console de manutenção do Unified Manager. Para obter mais informações, link:../config/concept_configure_unified_manager.html["Configurando o Active IQ Unified Manager"]consulte .

====


== Conexões do servidor do Unified Manager

Você deve configurar seu firewall para abrir portas que habilitem a comunicação entre o servidor do Unified Manager e sistemas de armazenamento gerenciados, servidores e outros componentes. Se uma porta não estiver aberta, a comunicação falhará.

Dependendo do seu ambiente, você pode optar por modificar as portas e protocolos usados pelo servidor do Unified Manager para se conetar a destinos específicos.

O servidor Unified Manager se coneta, usando os seguintes protocolos e portas, aos sistemas de storage gerenciado, servidores e outros componentes:

[cols="4*"]
|===
| Destino | Protocolo | Porta | Descrição 


 a| 
Sistema de storage
 a| 
HTTPS
 a| 
443/TCP
 a| 
Usado para monitorar e gerenciar sistemas de storage.



 a| 
Sistema de storage
 a| 
NDMP
 a| 
10000/TCP
 a| 
Usado para certas operações de restauração do Snapshot.



 a| 
Servidor AutoSupport
 a| 
HTTPS
 a| 
443
 a| 
Usado para enviar informações do AutoSupport. Requer o acesso à Internet para executar esta função.



 a| 
Servidor de autenticação
 a| 
LDAP
 a| 
389
 a| 
Usado para fazer solicitações de autenticação e solicitações de pesquisa de usuários e grupos.



 a| 
LDAPS
 a| 
636
 a| 
Usado para comunicação LDAP segura.



 a| 
Servidor de correio
 a| 
SMTP
 a| 
25
 a| 
Usado para enviar e-mails de notificação de alerta.



 a| 
Emissor de trap SNMP
 a| 
SNMPv1 ou SNMPv3
 a| 
162/UDP
 a| 
Usado para enviar armadilhas SNMP de notificação de alerta.



 a| 
Servidor de provedor de dados externo
 a| 
TCP
 a| 
2003
 a| 
Usado para enviar dados de desempenho para um provedor de dados externo, como o Graphite.



 a| 
Servidor NTP
 a| 
NTP
 a| 
123/UDP
 a| 
Usado para sincronizar a hora no servidor do Unified Manager com um servidor de hora NTP externo. (Somente sistemas VMware)



 a| 
AMQP QPID broker
 a| 
TCP/IP
 a| 
56072
 a| 
Usado para comunicação de mensagens internas.



 a| 
AMQP QPID broker
 a| 
WebSocket sobre TCP
 a| 
56080
 a| 
Usado para ouvir nessa porta as mensagens recebidas do ONTAP (agente de nuvem).



 a| 
AMQP QPID broker
 a| 
WebSocket sobre TCP
 a| 
56443
 a| 
Usado para ouvir nessa porta as mensagens recebidas do ONTAP (agente de nuvem). A comunicação através desta porta suporta encriptação fornecida por TLS ou SSL.



 a| 
Syslog
 a| 
UDP
 a| 
514
 a| 
Usado pelo Unified Manager para enviar logs de auditoria para um servidor syslog remoto.

|===