---
permalink: install-windows/task_upgrade_to_unified_manager_on_microsoft_windows.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: Você pode atualizar o Unified Manager baixando e executando o arquivo de instalação na plataforma Windows. 
---
= Atualizando o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar o Unified Manager 9,13 ou 9,14 para 9,16 baixando e executando o arquivo de instalação na plataforma Windows.

*O que você vai precisar*

* O sistema no qual você está atualizando o Unified Manager deve atender aos requisitos de sistema e software.
+
link:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisitos do sistema de hardware"]Consulte .

+
link:reference_windows_software_and_installation_requirements.html["Requisitos de software e instalação do Windows"]Consulte .

+
[NOTE]
====
A partir do Unified Manager 9,5, o OpenJDK é fornecido no pacote de instalação e instalado automaticamente. O Oracle Java não é suportado a partir do Unified Manager 9,5.

====
+
[NOTE]
====
Certifique-se de que o Microsoft .NET 4.5.2 ou superior esteja instalado no seu sistema antes de iniciar a atualização.

====
* O MySQL Community Edition é atualizado automaticamente durante a atualização do Unified Manager. Se a versão instalada do MySQL no seu sistema for anterior à 8,0.34, o processo de atualização do Unified Manager atualizará automaticamente o MySQL para 8,0.34. Você não deve executar uma atualização autônoma de uma versão anterior do MySQL para 8,0.34.
* Todos os clusters são compatíveis, com exceção dos sistemas ASA R2.
* Você deve ter o administrador do Windows Privileges. Certifique-se de que o seu nome de utilizador não começa com um ponto de exclamação "!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`" !".
* Você deve ter credenciais válidas para fazer login no site de suporte da NetApp.
* Para evitar a perda de dados, você deve ter criado um backup da máquina do Unified Manager caso haja algum problema durante a atualização.
* Você deve ter espaço em disco adequado disponível para realizar a atualização.
+
O espaço disponível na unidade de instalação deve ser 2,5 GB maior do que o tamanho do diretório de dados. A atualização pára e exibe uma mensagem de erro indicando a quantidade de espaço a ser adicionado se não houver espaço livre suficiente.

* Durante a atualização, você pode ser solicitado a confirmar se deseja manter as configurações padrão anteriores para reter dados de desempenho por 13 meses ou alterá-los para 6 meses. Ao confirmar, os dados históricos de desempenho após 6 meses são purgados.
* Antes de atualizar, você deve fechar todos os arquivos ou pastas abertos em _<InstallDir>_ e _diretório de dados MySQL_.
* Se tiver um software antivírus ativo instalado no sistema Windows, a atualização do Unified Manager poderá falhar. Você deve desativar todo o software de verificação de vírus em seu sistema antes de atualizar o Unified Manager.


Durante o processo de atualização, o Unified Manager não está disponível. Você deve concluir todas as operações em execução antes de atualizar o Unified Manager.

Se o Unified Manager estiver emparelhado com uma instância do OnCommand Workflow Automation e houver novas versões de software disponíveis para ambos os produtos, será necessário desconetar os dois produtos e configurar uma nova conexão do Workflow Automation após a realização das atualizações. Se você estiver executando uma atualização para apenas um dos produtos, deverá fazer login no Workflow Automation após a atualização e verificar se ele ainda está adquirindo dados do Unified Manager.

.Passos
. Faça login no site de suporte da NetApp e navegue até a página de download do Gerenciador Unificado:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Site de suporte da NetApp"^].

. Selecione a versão necessária do Unified Manager e aceite o contrato de licença de usuários finais (EULA).
. Transfira o ficheiro de instalação do Unified Manager Windows ou o ficheiro zip para um diretório de destino no sistema Windows. Extraia o arquivo zip, se necessário, e navegue até o diretório onde o arquivo de instalação está localizado. Clique com o botão direito do rato e execute o ficheiro executável (.exe) do instalador do Unified Manager como administrador.
+
O Unified Manager solicita a seguinte mensagem:

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. Clique em *Yes* e, em seguida, clique em *Next*.
. Digite a senha de root do MySQL8 que foi definida durante a instalação e clique em *Next*.
. Inicie a IU da Web em uma nova janela em um navegador da Web compatível e faça login para usar a versão atualizada do Unified Manager.
. Se tiver um software antivírus ativo instalado no sistema Windows, certifique-se de excluir manualmente os seguintes caminhos da verificação antivírus após a conclusão da atualização:
+
** Diretório de dados do Unified Manager
** Diretório de instalação do Unified Manager
** Diretório de dados MySQL




[NOTE]
====
Para executar uma atualização silenciosa do Unified Manager, execute o seguinte comando:
`ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=<password> /qn /l*v <system_drive>:\install.log"`

====