---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: Você pode redefinir a senha JBoss específica da instância definida durante a instalação. Você pode redefinir a senha opcionalmente, caso seu site exija esse recurso de segurança para substituir a configuração de instalação do Unified Manager. Esta operação também altera a senha que o JBoss usa para acessar o MySQL. 
---
= Alterar a senha do JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode redefinir a senha JBoss específica da instância definida durante a instalação. Você pode redefinir a senha opcionalmente, caso seu site exija esse recurso de segurança para substituir a configuração de instalação do Unified Manager. Esta operação também altera a senha que o JBoss usa para acessar o MySQL.

*O que você vai precisar*

* Você deve ter o Privileges de administrador do Windows para o sistema no qual o Unified Manager está instalado.
* Você deve ter a senha para o usuário root do MySQL.
* Você deve ser capaz de acessar o script fornecido pelo NetApp `password.bat` no diretório
+
`C:\Program Files\NetApp\essentials\bin`.



.Passos
. Faça login como usuário admin na máquina host do Unified Manager.
. Use o console dos Serviços do Windows para interromper os seguintes serviços do Unified Manager:
+
** Serviço de aquisição da NetApp Active IQ (Ocie-au)
** Serviço de servidor de gerenciamento NetApp Active IQ (Oncommandsvc)


. Inicie o `password.bat` script para iniciar o processo de alteração de senha:
+
`C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`

. Quando solicitado, insira a senha do usuário raiz do MySQL.
. Quando solicitado, digite a nova senha de usuário do JBoss e insira-a novamente para confirmação.
+
Observe que a senha deve ter entre 8 e 16 carateres, e deve conter pelo menos um dígito, carateres maiúsculos e minúsculos e pelo menos um desses carateres especiais:

+
`+!@%^*-_+=[]:<>.?/~+`

. Quando o script for concluído, inicie os serviços do Unified Manager usando o console do Windows Services:
+
** Serviço de servidor de gerenciamento NetApp Active IQ (Oncommandsvc)
** Serviço de aquisição da NetApp Active IQ (Ocie-au)


. Depois que todos os serviços forem iniciados, você poderá fazer login na IU do Unified Manager.

