---
permalink: config/task_change_local_user_password.html 
sidebar: sidebar 
keywords: change, local, user, password 
summary: Você pode alterar sua senha de login de usuário local para evitar possíveis riscos de segurança. 
---
= Alterar a palavra-passe do utilizador local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar sua senha de login de usuário local para evitar possíveis riscos de segurança.

*O que você vai precisar*

Você deve estar conetado como um usuário local.

As senhas para o usuário de manutenção e para usuários remotos não podem ser alteradas usando estas etapas. Para alterar uma palavra-passe de utilizador remoto, contacte o administrador da palavra-passe. Para alterar a senha do usuário de manutenção, link:task_use_maintenance_console.html["Utilizar a consola de manutenção"]consulte .

.Passos
. Faça login no Unified Manager.
. Na barra de menu superior, clique no ícone do usuário e, em seguida, clique em *alterar senha*.
+
A opção *alterar senha* não será exibida se você for um usuário remoto.

. Na caixa de diálogo alterar senha, insira a senha atual e a nova senha.
. Clique em *Salvar*.


Se o Unified Manager estiver configurado em uma configuração de alta disponibilidade, você deverá alterar a senha no segundo nó da configuração. Ambas as instâncias devem ter a mesma senha.
