---
permalink: config/task_test_configuration_of_authentication_servers_um_6_0.html 
sidebar: sidebar 
keywords: test, configuration, authentication servers 
summary: Você pode validar a configuração de seus servidores de autenticação para garantir que o servidor de gerenciamento seja capaz de se comunicar com eles. É possível validar a configuração pesquisando um usuário remoto ou grupo remoto de seus servidores de autenticação e autenticando-os usando as configurações configuradas. 
---
= Testando a configuração dos servidores de autenticação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode validar a configuração de seus servidores de autenticação para garantir que o servidor de gerenciamento seja capaz de se comunicar com eles. É possível validar a configuração pesquisando um usuário remoto ou grupo remoto de seus servidores de autenticação e autenticando-os usando as configurações configuradas.

*O que você vai precisar*

* Você deve ter habilitado a autenticação remota e configurado o serviço de autenticação para que o servidor do Unified Manager possa autenticar o usuário remoto ou o grupo remoto.
* Você deve ter adicionado seus servidores de autenticação para que o servidor de gerenciamento possa pesquisar o usuário remoto ou grupo remoto desses servidores e autenticá-los.
* Tem de ter a função Administrador de aplicações.


Se o serviço de autenticação estiver definido como ative Directory e se você estiver validando a autenticação de usuários remotos que pertencem ao grupo principal do servidor de autenticação, as informações sobre o grupo principal não serão exibidas nos resultados de autenticação.

.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Autenticação remota*.
. Clique em *Test Authentication*.
. Na caixa de diálogo testar usuário, especifique o nome de usuário e a senha do usuário remoto ou o nome de usuário do grupo remoto e clique em *Teste*.
+
Se estiver a autenticar um grupo remoto, não deve introduzir a palavra-passe.


