---
permalink: config/task_regenerate_client_certificate.html 
sidebar: sidebar 
keywords: client certificate, regenerate, validity, maintenance console 
summary: Você pode usar o console de manutenção para regenerar seu certificado de cliente do Unified Manager. 
---
= Regenerar o certificado do cliente do Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o console de manutenção para regenerar seu certificado de cliente do Unified Manager.  Seu certificado tem um período de validade estendido de cinco anos.

.Passos
. Efetue login como usuário de manutenção.
. Selecione *Regenerar Certificado do Cliente* e pressione *Enter*.
. Se o sistema solicitar autenticação, insira as credenciais necessárias.
. Selecione *Confirmar regeneração* e pressione *Enter*.
. Após o certificado ser regenerado, reinicie o serviço do Unified Manager para aplicar as alterações.
. Para verificar o certificado atualizado, faça login no ONTAP.  Visualize o status do certificado do cliente e o status de validade.


*Informações relacionadas*  https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html["Gerenciar certificados ONTAP com o System Manager"^]
