---
permalink: config/task_set_session_inactivity_timeout.html 
sidebar: sidebar 
keywords: inactivity, timeout 
summary: 'Você pode especificar o valor de tempo limite de inatividade do Unified Manager para que a sessão seja encerrada automaticamente após um determinado período de tempo. Por padrão, o tempo limite é definido para 4.320 minutos (72 horas).' 
---
= Definir o tempo limite de inatividade da sessão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode especificar o valor de tempo limite de inatividade do Unified Manager para que a sessão seja encerrada automaticamente após um determinado período de tempo. Por padrão, o tempo limite é definido para 4.320 minutos (72 horas).

*O que você vai precisar*

Tem de ter a função Administrador de aplicações.

Esta definição afeta todas as sessões de utilizador com sessão iniciada.

[NOTE]
====
Essa opção não estará disponível se você tiver habilitado a autenticação SAML (Security Assertion Markup Language).

====
.Passos
. No painel de navegação à esquerda, clique em *Geral* > *Definições da funcionalidade*.
. Na página *Configurações de recursos*, especifique o tempo limite de inatividade escolhendo uma das seguintes opções:
+
[cols="2*"]
|===
| Se você quiser... | Então faça isso... 


 a| 
Não tenha tempo limite definido para que a sessão nunca seja fechada automaticamente
 a| 
No painel *tempo limite de inatividade*, mova o botão deslizante para a esquerda (Desligado) e clique em *aplicar*.



 a| 
Defina um número específico de minutos como o valor de tempo limite
 a| 
No painel *tempo limite de inatividade*, mova o botão deslizante para a direita (ligado), especifique o valor de tempo limite de inatividade em minutos e clique em *aplicar*.

|===

