---
permalink: config/task_disable_nested_groups_from_remote_authentication.html 
sidebar: sidebar 
keywords: disable, nested groups, remote, authentication 
summary: Se a autenticação remota estiver ativada, você poderá desativar a autenticação de grupo aninhado para que somente usuários individuais, e não membros de grupo, possam se autenticar remotamente no Unified Manager. Você pode desativar grupos aninhados quando quiser melhorar o tempo de resposta de autenticação do ative Directory. 
---
= Desativando grupos aninhados da autenticação remota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se a autenticação remota estiver ativada, você poderá desativar a autenticação de grupo aninhado para que somente usuários individuais, e não membros de grupo, possam se autenticar remotamente no Unified Manager. Você pode desativar grupos aninhados quando quiser melhorar o tempo de resposta de autenticação do ative Directory.

*O que você vai precisar*

* Tem de ter a função Administrador de aplicações.
* A desativação de grupos aninhados só é aplicável ao usar o ative Directory.


Desativar o suporte para grupos aninhados no Unified Manager pode reduzir o tempo de autenticação. Se o suporte a grupos aninhados estiver desativado e se um grupo remoto for adicionado ao Unified Manager, os usuários individuais deverão ser membros do grupo remoto para se autenticar no Unified Manager.

.Passos
. No painel de navegação esquerdo, clique em *Geral* > *Autenticação remota*.
. Marque a caixa *Desativar Pesquisa de grupos aninhados*.
. Clique em *Salvar*.

