---
permalink: install-linux/task_install_unified_manager_linux.html 
sidebar: sidebar 
keywords: install, unified manager 
summary: É possível instalar o Unified Manager em uma plataforma Red Hat Enterprise Linux ou CentOS física ou virtual. 
---
= Instalar o Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível instalar o Unified Manager em uma plataforma Red Hat Enterprise Linux ou CentOS física ou virtual.

*O que você vai precisar*

* O sistema no qual você deseja instalar o Unified Manager deve atender aos requisitos de sistema e software.
+
link:concept_virtual_infrastructure_or_hardware_system_requirements.html["Requisitos do sistema de hardware"]Consulte .

+
link:reference_red_hat_and_centos_software_and_installation_requirements.html["Requisitos de software e instalação do Linux"]Consulte .

* Você deve ter baixado o arquivo do Gerenciador Unificado `.zip` do site de suporte da NetApp para o sistema de destino.
* Você deve ter verificado a integridade do arquivo baixado `.zip`.
* Você deve ter um navegador da Web compatível.
* O software de emulação de terminal deve ter o scrollback habilitado.


O sistema Red Hat Enterprise Linux ou CentOS pode ter todas as versões necessárias do software de suporte necessário (Java, MySQL, utilitários adicionais) instalado, apenas alguns dos softwares necessários instalados, ou pode ser um sistema recém-instalado sem nenhum dos softwares necessários instalados.

.Passos
. Faça login no servidor no qual você está instalando o Unified Manager.
. Digite os comandos apropriados para avaliar qual software pode exigir instalação ou atualização no sistema de destino para suportar a instalação:
+
[cols="2*"]
|===
| Software necessário e versão mínima | Comando para verificar o software e a versão 


 a| 
OpenJDK versão 11.0.21
 a| 
`java -version`



 a| 
MySQL 8.0.34 Community Edition
 a| 
`rpm -qa | grep -i mysql`



 a| 
p7zip 16,02
 a| 
`rpm -qa | grep p7zip`

|===
. Se a versão instalada do MySQL for anterior ao MySQL 8.0.34 Community Edition, digite o seguinte comando para desinstalá-lo:
+
`rpm -e <mysql_package_name>`

+
Se você receber erros de dependência, você deve adicionar a `--nodeps` opção para desinstalar o componente.

. Navegue até o diretório em que você baixou o arquivo de instalação `.zip` e expanda o pacote do Unified Manager:
+
`unzip ActiveIQUnifiedManager-_<version>_.zip`

+
Os `.rpm` módulos necessários para o Unified Manager são descompactados para o diretório de destino.

. Verifique se o seguinte módulo está disponível no diretório:
+
`ls *.rpm`

+
`netapp-um<version>.x86_64.rpm`

. Execute o script de pré-instalação para garantir que não haja configurações de sistema ou qualquer software instalado que possa entrar em conflito com a instalação do Unified Manager:
+
`sudo ./pre_install_check.sh`

+
O script de pré-instalação verifica se o sistema tem uma assinatura válida do Red Hat Enterprise Linux e se ele tem acesso aos repositórios de software necessários. Se o script identificar quaisquer problemas, você deve corrigir os problemas antes de instalar o Unified Manager.

+
Para o sistema Red Hat Enterprise Linux 8, se você tiver repositórios internos com JDK 11 - OpenJDK, p7zip e outros pacotes de software fornecidos pelo repositório AppStream, você deve desativar o repositório AppStream e instalar o MySQL Community Server. Execute o seguinte comando:

+
[listing]
----
# sudo yum --disablerepo=rhel-8-for-x86_64-appstream-rpms install  mysql-community-server
----
. *Opcional:* você deve executar o passo 7 somente se o seu sistema não estiver conetado à internet e você tiver que baixar manualmente os pacotes necessários para a sua instalação. Se o seu sistema tiver acesso à Internet e todos os pacotes necessários estiverem disponíveis, vá para o passo 8. Para sistemas que não estejam conetados à Internet ou que não estejam usando os repositórios Red Hat Enterprise Linux, execute as etapas a seguir para determinar se você está faltando algum pacote necessário e, em seguida, faça o download desses pacotes:
+
.. No sistema em que você está instalando o Unified Manager, veja a lista de pacotes disponíveis e indisponíveis
`yum install netapp-um<version>.x86_64.rpm --assumeno`
+
Os itens na seção "'Instalando:'" são os pacotes que estão disponíveis no diretório atual, e os itens na seção "'Instalando para dependências:'" são os pacotes que estão faltando no seu sistema.

.. Em um sistema que tenha acesso à Internet, baixe os pacotes ausentes:
+
`yum install <package_name> --downloadonly --downloaddir=.`

+
[NOTE]
====
Como o plug-in "yum-plugin-downloadonly" nem sempre está ativado em sistemas Red Hat Enterprise Linux, você pode precisar habilitar a funcionalidade para baixar um pacote sem instalá-lo:
`yum install yum-plugin-downloadonly`

====
.. Copie os pacotes ausentes do sistema conetado à Internet para o sistema de instalação.


. Como usuário raiz, ou usando `sudo`, execute o seguinte comando para instalar o software:
+
`yum install netapp-um<version>.x86_64.rpm`

+
Este comando instala os pacotes .rpm, todos os outros softwares de suporte necessários e o software Unified Manager.

+
Se a instalação falhar com o erro GPG NOKEY , use `rpm --import` para importar as chaves de um URL:

+
`rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022`

+
[NOTE]
====
Não tente instalar usando comandos alternativos (como `rpm -ivh` ). Uma instalação bem-sucedida do Unified Manager em um sistema Red Hat Enterprise Linux ou CentOS requer que todos os arquivos do Unified Manager e arquivos relacionados sejam instalados em uma ordem específica em uma estrutura de diretório específica que é aplicada automaticamente pelo `yum install netapp-um<version>.x86_64.rpm` comando.

====
. Ignore a notificação de e-mail exibida imediatamente após as mensagens de instalação.
+
O e-mail notifica o usuário raiz de uma falha inicial do cron job, o que não tem efeito adverso na instalação.

. Depois que as mensagens de instalação estiverem concluídas, role para trás pelas mensagens até que você veja a mensagem na qual o sistema exibe um endereço IP ou URL para a IU da Web do Unified Manager, o nome do usuário de manutenção (umadmin) e uma senha padrão.
+
A mensagem é semelhante à seguinte:

+
[listing]
----
Active IQ Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----
. Registre o endereço IP ou URL, o nome de usuário atribuído (umadmin) e a senha atual.
. Se você criou uma conta de usuário umadmin com um diretório inicial personalizado antes de instalar o Unified Manager, você deve especificar o shell de login do usuário umadmin:
+
`usermod -s /bin/maintenance-user-shell.sh umadmin`



Acesse a IU da Web para alterar a senha padrão do usuário umadmin e execute a configuração inicial do Unified Manager, conforme descrito em link:../config/concept_configure_unified_manager.html["Configurando o Active IQ Unified Manager"]. É obrigatório alterar a senha padrão do usuário umadmin.
