---
permalink: install-linux/task_change_jboss_password.html 
sidebar: sidebar 
keywords: change, jboss password 
summary: Você pode redefinir a senha JBoss específica da instância definida durante a instalação. Você pode redefinir a senha opcionalmente, caso seu site exija esse recurso de segurança para substituir a configuração de instalação do Unified Manager. Esta operação também altera a senha que o JBoss usa para acessar o MySQL. 
---
= Alterar a senha do JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode redefinir a senha JBoss específica da instância definida durante a instalação. Você pode redefinir a senha opcionalmente, caso seu site exija esse recurso de segurança para substituir a configuração de instalação do Unified Manager. Esta operação também altera a senha que o JBoss usa para acessar o MySQL.

* É necessário ter acesso de usuário raiz ao sistema Red Hat Enterprise Linux ou CentOS no qual o Unified Manager está instalado.
* Você deve ser capaz de acessar o script fornecido pelo NetApp `password.sh` no diretório `/opt/netapp/essentials/bin`.


.Passos
. Inicie sessão como utilizador raiz no sistema.
. Pare os serviços do Unified Manager inserindo os seguintes comandos na ordem mostrada:
+
`systemctl stop ocieau`

+
`systemctl stop ocie`

+
Não pare o software MySQL associado.

. Digite o seguinte comando para iniciar o processo de alteração de senha:
+
`/opt/netapp/essentials/bin/password.sh resetJBossPassword`

. Quando solicitado, digite a nova senha do JBoss e insira-a uma segunda vez para confirmação.
+
Observe que a senha deve ter entre 8 e 16 carateres, e deve conter pelo menos um dígito, carateres maiúsculos e minúsculos e pelo menos um desses carateres especiais:

+
`+!@%^*-_+=[]:<>.?/~+`

. Quando o script for concluído, inicie os serviços do Unified Manager inserindo os seguintes comandos na ordem mostrada:
+
`systemctl start ocie`

+
`systemctl start ocieau`

. Depois que todos os serviços forem iniciados, você poderá fazer login na IU do Unified Manager.

