---
permalink: events/reference_nvme_namespace_events.html 
sidebar: sidebar 
keywords: nvme, namespace, events, impact area, availability, performance 
summary: Os eventos de namespace do NVMe fornecem informações sobre o status de seus namespaces para que você possa monitorar se há possíveis problemas. Os eventos são agrupados por área de impactos e incluem o nome do evento e da armadilha, o nível de impactos, o tipo de origem e a gravidade. 
---
= Eventos de namespace NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os eventos de namespace do NVMe fornecem informações sobre o status de seus namespaces para que você possa monitorar se há possíveis problemas. Os eventos são agrupados por área de impactos e incluem o nome do evento e da armadilha, o nível de impactos, o tipo de origem e a gravidade.

Um asterisco (*) identifica eventos EMS que foram convertidos para eventos do Unified Manager.



== Área de impactos: Disponibilidade

|===
| Nome do evento (Nome da armadilha) | Nível de impactos | Tipo de origem | Gravidade 


 a| 
NVMeNS Offline *(nvmeNamespaceStatusOffline)
 a| 
Evento
 a| 
Namespace
 a| 
Informações



 a| 
NVMeNS Online *(nvmeNamespaceStatusOnline)
 a| 
Evento
 a| 
Namespace
 a| 
Informações



 a| 
NVMeNS fora do espaço *(nvmeNamespaceSpaceOutOfSpace)
 a| 
Risco
 a| 
Namespace
 a| 
Aviso



 a| 
NVMeNS Destroy *(nvmeNamespaceDestroy)
 a| 
Evento
 a| 
Namespace
 a| 
Informações

|===


== Área de impactos: Desempenho

|===
| Nome do evento (Nome da armadilha) | Nível de impactos | Tipo de origem | Gravidade 


 a| 
Limite crítico de IOPS do NVMe violado (ocumNvmeNamespaceIopsIncident)
 a| 
Incidente
 a| 
Namespace
 a| 
Crítico



 a| 
Limite de aviso de IOPS do namespace NVMe violado (ocumNvmeNamespaceIopsWarning)
 a| 
Risco
 a| 
Namespace
 a| 
Aviso



 a| 
Limite crítico violado(ocumNvmeNamespaceMbpsIncident)
 a| 
Incidente
 a| 
Namespace
 a| 
Crítico



 a| 
Limite de aviso de MB/s de NVMe violado(ocumNvmeNamespaceMbpsWarning)
 a| 
Risco
 a| 
Namespace
 a| 
Aviso



 a| 
Latência do namespace NVMe ms/op Critical Threshold violado(ocumNvmeNamespaceLatencyIncident)
 a| 
Incidente
 a| 
Namespace
 a| 
Crítico



 a| 
Limite de aviso ms/op de latência do namespace NVMe violado(ocumNvmeNamespaceLatencyWarning)
 a| 
Risco
 a| 
Namespace
 a| 
Aviso



 a| 
Latência do namespace NVMe e limite crítico de IOPS violado (ocumNvmeNamespaceLatencyIopsIncident)
 a| 
Incidente
 a| 
Namespace
 a| 
Crítico



 a| 
Latência do namespace NVMe e limite de aviso de IOPS violado (ocumNvmeNamespaceLatencyIopsWarning)
 a| 
Risco
 a| 
Namespace
 a| 
Aviso



 a| 
Latência do namespace NVMe e limite crítico de MB/s violado(ocumNvmeNamespaceLatencyMbpsIncident)
 a| 
Incidente
 a| 
Namespace
 a| 
Crítico



 a| 
Latência do namespace NVMe e limite de aviso de MB/s violado(ocumNvmeNamespaceLatencyMbpsWarning)
 a| 
Risco
 a| 
Namespace
 a| 
Aviso

|===