---
permalink: events/reference_snapmirror_and_vault_relationship_events.html 
sidebar: sidebar 
keywords: asynchronous, mirror, vault, relationship, events, impact area, protection 
summary: Os eventos de relacionamento de espelhamento assíncrono e cofre fornecem informações sobre o status de suas relações assíncronas do SnapMirror e do Vault para que você possa monitorar possíveis problemas. Os eventos Asynchronous Mirror e Vault relation são compatíveis tanto para relacionamentos de proteção de volume quanto Storage VM. Mas apenas as relações do Vault não são suportadas para recuperação de desastres da Storage VM. Os eventos são agrupados por área de impactos e incluem o nome do evento e da armadilha, o nível de impactos, o tipo de origem e a gravidade. 
---
= Eventos de relacionamento com o Asynchronous Mirror e o Vault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os eventos de relacionamento de espelhamento assíncrono e cofre fornecem informações sobre o status de suas relações assíncronas do SnapMirror e do Vault para que você possa monitorar possíveis problemas. Os eventos Asynchronous Mirror e Vault relation são compatíveis tanto para relacionamentos de proteção de volume quanto Storage VM. Mas apenas as relações do Vault não são suportadas para recuperação de desastres da Storage VM. Os eventos são agrupados por área de impactos e incluem o nome do evento e da armadilha, o nível de impactos, o tipo de origem e a gravidade.



== Área de impactos: Proteção

[NOTE]
====
Os eventos de relacionamentos do SnapMirror e do Vault também são gerados para VMs de armazenamento protegidas pela recuperação de desastres da VM de armazenamento, mas não para quaisquer relações de objetos constituintes.

====
|===
| Nome do evento (Nome da armadilha) | Nível de impactos | Tipo de origem | Gravidade 


 a| 
Espelhamento assíncrono e cofre não saudável(ocumEvtMirrorVaultRelationshipUnHealthy)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Aviso



 a| 
Espelhamento assíncrono e Vault quebrado-off(ocumEvtMirrorVaultRelationshipStateBrokenoff)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro



 a| 
Falha na inicialização do espelhamento assíncrono e do Vault(ocumEvtMirrorVaultRelationshipInitializeFailed)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro



 a| 
Falha na atualização assíncrona do espelho e do Vault(ocumEvtMirrorVaultRelationshipUpdateFailed)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro



 a| 
Erro assíncrono do espelhamento e do Vault Lag(ocumEvtMirrorVaultRelationshipLagError)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro



 a| 
Espelho assíncrono e Vault Lag Warning(ocumEvtMirrorVaultRelationshipLagWarning)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Aviso



 a| 
Espelhamento assíncrono e Vault Resync falhou(ocumEvtMirrorVaultRelationshipResyncFailed)
 a| 
Risco
 a| 
Relação de SnapMirror
 a| 
Erro

|===
[NOTE]
====
O evento "update failure" (Falha na atualização do SnapMirror) é gerado pelo portal Active IQ (Config Advisor).

====