---
permalink: events/task_exclude_disaster_recovery_destination_volumes_from_alerts.html 
sidebar: sidebar 
keywords: exclude, disaster, recovery, destination, volumes, generate, alerts 
summary: Ao configurar alertas de volume, você pode especificar uma cadeia de carateres na caixa de diálogo Alerta que identifica um volume ou grupo de volumes. No entanto, se você configurou a recuperação de desastres para SVMs, os volumes de origem e destino têm o mesmo nome, então você receberá alertas para ambos os volumes. 
---
= Exclusão da geração de alertas de volumes de destino de recuperação de desastres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao configurar alertas de volume, você pode especificar uma cadeia de carateres na caixa de diálogo Alerta que identifica um volume ou grupo de volumes. No entanto, se você configurou a recuperação de desastres para SVMs, os volumes de origem e destino têm o mesmo nome, então você receberá alertas para ambos os volumes.

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

Você pode desativar alertas de volumes de destino de recuperação de desastres excluindo volumes que tenham o nome do SVM de destino. Isso é possível porque o identificador para eventos de volume contém o nome do SVM e o nome do volume no formato "<svm_name>:/<volume_name>".

O exemplo abaixo mostra como criar alertas para o volume "vol1" no SVM principal "VS1", mas exclui que o alerta seja gerado em um volume com o mesmo nome no SVM "VS1-dr".

Execute as seguintes etapas na caixa de diálogo Adicionar alerta:

.Passos
. Clique em *Nome* e insira um nome e uma descrição para o alerta.
. Clique em *recursos* e selecione a guia *incluir*.
+
.. Selecione *volume* na lista suspensa e digite *`vol1`* no campo *Nome contém* para exibir os volumes cujo nome contém "vol1".
.. Selecione *<<All Volumes whose name contains 'vol1'>> na área *recursos disponíveis* e mova-a para a área *recursos selecionados*.


. Selecione a guia *Excluir*, selecione *volume*, digite *`vs1-dr`* no campo *Nome contém* e clique em *Adicionar*.
+
Isso exclui que o alerta seja gerado para o volume "vol1" na SVM "VS1-dr".

. Clique em *Eventos* e selecione o evento ou eventos que deseja aplicar ao volume ou volumes.
. Clique em *ações* e selecione o nome do usuário que receberá o e-mail de alerta no campo *alertar esses usuários*.
. Configure quaisquer outras opções nesta página para emitir traps SNMP e executar um script e, em seguida, clique em *Salvar*.

