---
permalink: data-protection/task_quiesce_protection_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: quiesce, protection, relationship, volume, health details page 
summary: Você pode silenciar uma relação de proteção para impedir temporariamente a ocorrência de transferências de dados. Você pode desativar um relacionamento quando quiser criar uma cópia Snapshot de um volume de destino do SnapMirror que contém um banco de dados e deseja garantir que seu conteúdo esteja estável durante a cópia Snapshot. 
---
= Mantendo uma relação de proteção a partir da página de detalhes de volume / Saúde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode silenciar uma relação de proteção para impedir temporariamente a ocorrência de transferências de dados. Você pode desativar um relacionamento quando quiser criar uma cópia Snapshot de um volume de destino do SnapMirror que contém um banco de dados e deseja garantir que seu conteúdo esteja estável durante a cópia Snapshot.

*O que você vai precisar*

* Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.
* Você deve ter configurado o Workflow Automation.


A ação quiesce não é exibida nos seguintes casos:

* Se as configurações RBAC não permitirem essa ação, por exemplo, se você tiver apenas Privileges de operador
* Quando o ID do volume é desconhecido, por exemplo, quando você tem uma relação entre clusters e o cluster de destino ainda não foi descoberto
* Quando você não emparelhou o Workflow Automation e o Unified Manager


.Passos
. Na guia *proteção* da página de detalhes *volume / Saúde*, clique com o botão direito do Mouse na relação na exibição de topologia para a relação de proteção que você deseja silenciar.
. Selecione *quiesce* no menu.
. Clique em *Yes* para continuar.
+
O status do trabalho quiesce é exibido na parte superior da página de detalhes de volume / Saúde, juntamente com um link para os detalhes do trabalho.

. Clique no link *Exibir detalhes* para ir para a página de detalhes *trabalho* para obter detalhes adicionais e progresso do trabalho.
. *Opcional:* clique na seta para trás do seu navegador para retornar à página de detalhes *volume / Saúde*.
+
O trabalho quiesce é concluído quando todas as tarefas de trabalho são concluídas com êxito.


