---
permalink: data-protection/task_resume_scheduled_transfers_voldtls_page.html 
sidebar: sidebar 
keywords: resume schedule, transfers, quiesce, relationship,  volume, health details page 
summary: 'Depois de ter silenciado um relacionamento para impedir que as transferências agendadas ocorram, você pode usar Resume (Retomar) na página volume / detalhes de saúde para reativar as transferências agendadas para que os dados na origem ou no volume primário sejam protegidos. As transferências são retomadas a partir de um ponto de verificação, se houver, no próximo intervalo de transferência programado.' 
---
= Retomar as transferências agendadas numa relação quiesced a partir da página de detalhes de volume / Saúde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de ter silenciado um relacionamento para impedir que as transferências agendadas ocorram, você pode usar *Resume* na página de detalhes de volume / Saúde para reativar as transferências agendadas para que os dados na origem ou no volume primário sejam protegidos. As transferências são retomadas a partir de um ponto de verificação, se houver, no próximo intervalo de transferência programado.

*O que você vai precisar*

* Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.
* Você deve ter configurado o Workflow Automation.


.Passos
. Na guia *proteção* da página de detalhes *volume / Saúde*, clique com o botão direito do Mouse na exibição de topologia uma relação quiesced que você deseja retomar.
+
Em alternativa, selecione *Resume* no menu *ações* > *relacionamento*.

. Na caixa de diálogo *Resume*, clique em *Continue*.
+
Regressa à página de detalhes de volume / Saúde.

. Para visualizar as tarefas relacionadas e acompanhar o seu progresso, clique no link do trabalho que é exibido na parte superior da página de detalhes *volume / Saúde*.
. Na página de detalhes do *trabalho*, clique em *Atualizar* para atualizar a lista de tarefas e os detalhes da tarefa associados ao trabalho de configuração de proteção e para determinar quando o trabalho está concluído.
+
Após a conclusão dos trabalhos, as transferências de dados são retomadas no próximo intervalo de transferência programado.


