---
permalink: data-protection/task_retry_failed_protection_job.html 
sidebar: sidebar 
keywords: retry, failed, protection job 
summary: Depois de tomar medidas para corrigir um trabalho de proteção com falha, você pode usar tentar novamente para executar o trabalho novamente. Tentar novamente um trabalho cria um novo trabalho usando o ID do trabalho original. 
---
= Tentar novamente um trabalho de proteção com falha
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de tomar medidas para corrigir um trabalho de proteção com falha, você pode usar *Repetir* para executar o trabalho novamente. Tentar novamente um trabalho cria um novo trabalho usando o ID do trabalho original.

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

Você pode tentar novamente apenas um trabalho com falha de cada vez. Selecionar mais de um trabalho desativa o botão *Repetir*. Apenas os trabalhos do tipo Configuração de proteção e operação de relação de proteção podem ser tentados novamente.

.Passos
. No painel de navegação esquerdo, clique em *proteção* > *empregos*.
. Na lista de trabalhos, selecione uma única tarefa de tipo de operação de relação de proteção ou Configuração de proteção com falha.
+
O botão *Repetir* está ativado.

. Clique em *Repetir*.
+
O trabalho é reiniciado.


