---
permalink: data-protection/task_create_snapmirror_relationship_from_health_volumes.html 
sidebar: sidebar 
keywords: create, snapmirror, protection, relationship, health, volumes view 
summary: 'Usando a exibição integridade: Todos os volumes, você pode criar vários relacionamentos de proteção SnapMirror ao mesmo tempo, selecionando mais de um volume na mesma VM de storage.' 
---
= Criando uma relação de proteção SnapMirror a partir da visualização integridade: Todos os volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Usando a exibição integridade: Todos os volumes, você pode criar vários relacionamentos de proteção SnapMirror ao mesmo tempo, selecionando mais de um volume na mesma VM de storage.

*O que você vai precisar*

* Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.
* Você deve ter configurado o Workflow Automation.


O menu *Protect* não é exibido nas seguintes instâncias:

* Se as configurações RBAC não permitirem essa ação: Por exemplo, se você tiver apenas Privileges de operador
* Quando o ID do volume é desconhecido: Por exemplo, quando você tem uma relação entre clusters e o cluster de destino ainda não foi descoberto


.Passos
. Na exibição *Saúde: Todos os volumes*, selecione um volume que você deseja proteger.
+
Como alternativa, para criar vários relacionamentos de proteção no mesmo SVM, selecione um ou mais volumes na exibição Saúde: Todos os volumes e clique em *proteger* > *SnapMirror* na barra de ferramentas.

+
A caixa de diálogo Configurar proteção é exibida.

. Clique em *SnapMirror* para visualizar a guia *SnapMirror* e configurar as informações de destino.
. Clique em *Avançado* para definir a garantia de espaço, conforme necessário, e clique em *aplicar*.
. Preencha a área *informações de destino* e a área *Configurações de relacionamento* na guia *SnapMirror*.
. Clique em *aplicar*.
+
Você retorna à exibição Saúde: Todos os volumes.

. Clique no link trabalho de configuração de proteção na parte superior da exibição *Saúde: Todos os volumes*.
+
Se estiver a criar apenas uma relação de proteçãoão, é apresentada a página Detalhes do trabalho; no entanto, se estiver a criar mais do que uma relação de proteçãoão, é apresentada uma lista de todos os trabalhos associados à operação de proteçãoão.

. Execute um dos seguintes procedimentos:
+
** Se tiver apenas um trabalho, clique em *Atualizar* para atualizar a lista de tarefas e os detalhes da tarefa associados ao trabalho de configuração de proteção e para determinar quando o trabalho está concluído.
** Se tiver mais de um trabalho:
+
... Clique num trabalho na lista de trabalhos.
... Clique em *Atualizar* para atualizar a lista de tarefas e os detalhes da tarefa associados ao trabalho de configuração de proteção e para determinar quando o trabalho está concluído.
... Use o botão *voltar* para retornar à lista filtrada e exibir outro trabalho.






Dependendo do SVM de destino especificado durante a configuração ou das opções habilitadas nas configurações avançadas, a relação SnapMirror resultante pode ser uma das várias variações possíveis:

* Se você especificou um SVM de destino que seja executado na mesma ou em uma versão mais recente do ONTAP em comparação com a do volume de origem, uma relação do SnapMirror baseada em replicação de bloco será o resultado padrão.
* Se você especificou um SVM de destino que seja executado na mesma ou em uma versão mais recente do ONTAP em comparação com a do volume de origem, mas ativou a replicação flexível de versão nas configurações avançadas, o resultado será uma relação do SnapMirror com a replicação flexível de versão.
* Se você especificou um SVM de destino que é executado em uma versão anterior do ONTAP do que a do volume de origem e a versão anterior dá suporte à replicação flexível de versão, uma relação do SnapMirror com a replicação flexível de versão será o resultado automático.

