---
permalink: data-protection/task_delete_resource_pools.html 
sidebar: sidebar 
keywords: delete, resource, pools 
summary: Você pode excluir pools de recursos quando eles não forem mais necessários. Por exemplo, você pode querer redistribuir os agregados de membros de um pool de recursos para vários outros pools de recursos, tornando o pool de recursos original obsoleto. 
---
= Excluindo pools de recursos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode excluir pools de recursos quando eles não forem mais necessários. Por exemplo, você pode querer redistribuir os agregados de membros de um pool de recursos para vários outros pools de recursos, tornando o pool de recursos original obsoleto.

*O que você vai precisar*

Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.

O botão *Delete* é ativado somente quando pelo menos um pool de recursos estiver selecionado.

.Passos
. No painel de navegação esquerdo, clique em *proteção* > *pools de recursos*.
. Selecione o pool de recursos que deseja excluir.
. Clique em *Excluir*.
+
O pool de recursos é removido da lista de pool de recursos e seus agregados são removidos da lista de membros.


