---
permalink: data-protection/task_quiesce_protection_relationship_from_volume_relationships.html 
sidebar: sidebar 
keywords: quiesce, protection, relationship, volume, relationships page 
summary: Na página relacionamentos de volume, você pode silenciar uma relação de proteção para impedir temporariamente a ocorrência de transferências de dados. Você pode desativar um relacionamento quando quiser criar uma cópia Snapshot de um volume de destino do SnapMirror que contém um banco de dados e deseja garantir que seu conteúdo esteja estável durante a operação de cópia Instantânea. 
---
= Mantendo uma relação de proteção a partir da página relacionamentos de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na página relacionamentos de volume, você pode silenciar uma relação de proteção para impedir temporariamente a ocorrência de transferências de dados. Você pode desativar um relacionamento quando quiser criar uma cópia Snapshot de um volume de destino do SnapMirror que contém um banco de dados e deseja garantir que seu conteúdo esteja estável durante a operação de cópia Instantânea.

*O que você vai precisar*

* Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.
* Você deve ter configurado o Workflow Automation.


A ação quiesce não é exibida nos seguintes casos:

* Se as configurações RBAC não permitirem essa ação; por exemplo, se você tiver apenas Privileges de operador
* Quando o ID do volume é desconhecido; por exemplo, quando você tem uma relação entre clusters e o cluster de destino ainda não foi descoberto
* Quando você não emparelhou o Workflow Automation e o Unified Manager


.Passos
. Para obter transferências para um ou mais relacionamentos de proteção, na página *relacionamentos de volume*, selecione um ou mais volumes e, na barra de ferramentas, clique em *quiesce*.
+
A caixa de diálogo quiesce é exibida.

. Clique em *continuar*.
+
O status do trabalho quiesce é exibido na parte superior da página de detalhes de volume / Saúde, juntamente com um link para os detalhes do trabalho.

. Clique no link *Exibir detalhes* para ir para a página de detalhes *trabalho* para obter detalhes adicionais e progresso do trabalho.
. *Opcional:* clique na seta *voltar* no seu navegador para retornar à página *relacionamentos por volume*.
+
O trabalho quiesce é concluído quando todas as tarefas de trabalho são concluídas com êxito.


