---
permalink: data-protection/task_break_snapmirror_relationship_from_health_volume_details.html 
sidebar: sidebar 
keywords: break, snapmirror, relationship, volume, health details 
summary: Você pode quebrar uma relação de proteção da página de detalhes de volume / Saúde e interromper as transferências de dados entre um volume de origem e destino em uma relação do SnapMirror. Você pode interromper um relacionamento quando quiser migrar dados, para recuperação de desastres ou para teste de aplicações. O volume de destino é alterado para um volume de leitura e gravação. Você não pode quebrar um relacionamento SnapVault. 
---
= Quebrar uma relação de SnapMirror a partir da página de detalhes de volume / Saúde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode quebrar uma relação de proteção da página de detalhes de volume / Saúde e interromper as transferências de dados entre um volume de origem e destino em uma relação do SnapMirror. Você pode interromper um relacionamento quando quiser migrar dados, para recuperação de desastres ou para teste de aplicações. O volume de destino é alterado para um volume de leitura e gravação. Você não pode quebrar um relacionamento SnapVault.

*O que você vai precisar*

* Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.
* Você deve ter configurado o Workflow Automation.


.Passos
. Na guia *proteção* da página de detalhes *volume / Saúde*, selecione na topologia a relação do SnapMirror que deseja quebrar.
. Clique com o botão direito do rato no destino e selecione *Break* no menu.
+
É apresentada a caixa de diálogo Break Relationship (interromper relação).

. Clique em *continuar* para quebrar o relacionamento.
. Na topologia, verifique se o relacionamento está quebrado.

